import { CHARACTER_FACTIONS, getAvailableCharacters, getCharactersByFaction, getCharacterBaseId, getCharacterById } from '../battle/CharacterCatalog.js';
import { FormationStore } from '../battle/FormationStore.js';

export class FormationEditor {
  constructor({ mount, onFormationChanged, onApplyBattle }) { this.mount = mount || document.body; this.onFormationChanged = onFormationChanged || (() => {}); this.onApplyBattle = onApplyBattle || (() => {}); this.filter = CHARACTER_FACTIONS.all; this.formation = FormationStore.load(); this.activeSlot = 0; this.root = document.createElement('div'); this.root.className = 'formation-ui'; this.mount.appendChild(this.root); this.root.addEventListener('click', (e) => this.onClick(e)); this.refresh(); }
  setVisible(v) { this.root.style.display = v ? 'block' : 'none'; }
  onClick(e) { const slot = e.target.closest('[data-slot]'); const filter = e.target.closest('[data-filter]'); const character = e.target.closest('[data-character]'); const action = e.target.closest('[data-action]'); if (slot) { this.activeSlot = Number(slot.dataset.slot); return this.renderDynamic(); } if (filter) { this.filter = filter.dataset.filter; return this.renderDynamic(); } if (character) { FormationStore.setSlot(this.activeSlot, character.dataset.character); this.formation = FormationStore.load(); this.onFormationChanged(this.formation); return this.renderDynamic(); } if (action?.dataset.action === 'apply') this.onApplyBattle(this.formation); }
  renderDynamic() { const chars = this.filter === CHARACTER_FACTIONS.all ? getAvailableCharacters() : getCharactersByFaction(this.filter); const flat = (this.formation?.pages || []).flat(); const usedBaseIds = new Set(flat.filter(Boolean).map((id) => getCharacterBaseId(id)).filter(Boolean)); this.root.querySelector('.formation-slots').innerHTML = flat.map((id, i) => { const c = id ? getCharacterById(id) : null; return `<button class='formation-slot ${this.activeSlot === i ? 'is-active' : ''}' data-slot='${i}'>${c ? `<img src='${c.uiIcon?.primary || ''}' onerror="this.onerror=null;this.src='${c.uiIcon?.fallback || ''}'"><span>${c.label}</span>` : '<span>EMPTY</span>'}</button>`; }).join(''); this.root.querySelector('.formation-catalog-grid').innerHTML = chars.map((c) => `<button class='formation-character-card ${usedBaseIds.has(getCharacterBaseId(c.characterId)) ? 'is-used' : ''}' data-character='${c.characterId}'><img src='${c.uiIcon?.primary || ''}' onerror="this.onerror=null;this.src='${c.uiIcon?.fallback || ''}'"><span>${c.factionLabel || c.faction}</span><strong>${c.label}</strong><small>${c.statsSummary || `${c.characterId}`}</small></button>`).join(''); }
  refresh() { this.root.innerHTML = `<div class='formation-panel'><div class='formation-header'><h3>編成</h3></div><div class='formation-filters'>${Object.values(CHARACTER_FACTIONS).map((f) => `<button data-filter='${f}'>${f}</button>`).join('')}</div><div class='formation-slots'></div><div class='formation-catalog-scroll'><div class='formation-catalog-grid'></div></div><div class='formation-actions'><button data-action='apply'>Apply</button></div></div>`; this.renderDynamic(); }
}
