import { CHARACTER_FACTIONS, getAvailableCharacters, getCharactersByFaction, getCharacterBaseId, getCharacterById } from '../battle/CharacterCatalog.js';
import { FormationStore } from '../battle/FormationStore.js';

export class FormationEditor {
  constructor({ mount, onFormationChanged, onApplyBattle }) { this.mount = mount || document.body; this.onFormationChanged = onFormationChanged || (() => {}); this.onApplyBattle = onApplyBattle || (() => {}); this.filter = CHARACTER_FACTIONS.all; this.formation = FormationStore.load(); this.activeSlot = 0; this.applying = false; this.root = document.createElement('div'); this.root.className = 'formation-ui'; this.mount.appendChild(this.root); this.root.addEventListener('click', (e) => this.onClick(e)); this.refresh(); }
  setVisible(v) { this.root.classList.toggle('is-visible', !!v); }
  async onClick(e) { const action = e.target.closest('[data-action]'); if (action) { const type = action.dataset.action; if (type === 'apply' && !this.applying) { e.preventDefault(); e.stopPropagation(); const btn = this.root.querySelector('.apply-battle-button'); this.applying = true; if (btn) { btn.disabled = true; btn.textContent = 'Applying...'; } try { await this.onApplyBattle(this.formation); } catch (err) { console.error('[FormationEditor] apply failed', err); this.root.querySelector('.formation-action-hint').textContent = `Apply failed: ${err instanceof Error ? err.message : String(err)}`; } finally { this.applying = false; if (btn) { btn.disabled = false; btn.textContent = 'Apply Battle'; } } return; } if (type === 'clear') { FormationStore.setSlot(this.activeSlot, null); this.formation = FormationStore.load(); this.onFormationChanged(this.formation); return this.renderDynamic(); } if (type === 'reset') { FormationStore.reset(); this.formation = FormationStore.load(); this.onFormationChanged(this.formation); return this.renderDynamic(); } }
    const slot = e.target.closest('[data-slot]'); const filter = e.target.closest('[data-filter]'); const character = e.target.closest('[data-character]'); if (slot) { this.activeSlot = Number(slot.dataset.slot); return this.renderDynamic(); } if (filter) { this.filter = filter.dataset.filter; return this.renderDynamic(); } if (character) { FormationStore.setSlot(this.activeSlot, character.dataset.character); this.formation = FormationStore.load(); this.onFormationChanged(this.formation); return this.renderDynamic(); } }
  renderDynamic() { const chars = this.filter === CHARACTER_FACTIONS.all ? getAvailableCharacters() : getCharactersByFaction(this.filter); const flat = (this.formation?.pages || []).flat(); const usedBaseIds = new Set(flat.filter(Boolean).map((id) => getCharacterBaseId(id)).filter(Boolean)); this.root.querySelector('.formation-slots').innerHTML = flat.map((id, i) => { const c = id ? getCharacterById(id) : null; return `<button class='formation-slot ${this.activeSlot === i ? 'is-active' : ''}' data-slot='${i}'>${c ? `<img src='${c.uiIcon?.primary || ''}' onerror="this.onerror=null;this.src='${c.uiIcon?.fallback || ''}'"><span>${c.label}</span>` : '<span>EMPTY</span>'}</button>`; }).join(''); this.root.querySelector('.formation-catalog-grid').innerHTML = chars.map((c) => `<button class='formation-character-card ${usedBaseIds.has(getCharacterBaseId(c.characterId)) ? 'is-used' : ''}' data-character='${c.characterId}'><img src='${c.uiIcon?.primary || ''}' onerror="this.onerror=null;this.src='${c.uiIcon?.fallback || ''}'"><span>${c.factionLabel || c.faction}</span><strong>${c.label}</strong><small>${c.statsSummary || `${c.characterId}`}</small></button>`).join(''); }
  refresh() { this.root.innerHTML = `<div class='formation-panel'><section class='formation-main'><header class='formation-header'><h3>編成</h3><p>キャラを選び、右の Apply Battle で開始</p></header><section class='formation-slots-wrap'><div class='formation-slots'></div></section><section class='formation-catalog-section'><div class='formation-catalog-tabs'>${Object.values(CHARACTER_FACTIONS).map((f) => `<button data-filter='${f}'>${f}</button>`).join('')}</div><div class='formation-catalog-scroll'><div class='formation-catalog-grid'></div></div></section></section><aside class='formation-action-rail' aria-label='Formation actions'><button data-action='apply' class='apply-battle-button'>Apply Battle</button><button data-action='clear' class='secondary-action'>Clear Slot</button><button data-action='reset' class='secondary-action'>Reset Default</button><p class='formation-action-hint'>Apply Battleで戦闘開始</p></aside></div>`; this.renderDynamic(); }
}
