import { FormationEditor } from './FormationEditor.js';
import { PreviewUi } from '../preview/PreviewUi.js';
import { PreviewApp } from '../preview/PreviewApp.js';

const ok = (details = null) => ({ ok: true, errors: [], details });
const fail = (errors, details = null) => ({ ok: false, errors, details });
const readText = async (rel) => { const { readFile } = await import('node:fs/promises'); return readFile(new URL(rel, import.meta.url), 'utf8'); };
const defs = (css, sel) => (css.match(new RegExp(sel.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\s*\{', 'g')) || []).length;

export async function verifyFormationUsesSideActionRail() { const src = await readText('./FormationEditor.js'); const errors = []; if (!src.includes('formation-main')) errors.push('formation-main missing'); if (!src.includes('formation-action-rail')) errors.push('formation-action-rail missing'); if (!src.includes("data-action='apply' class='apply-battle-button'")) errors.push('apply button not in rail'); if (src.includes('formation-actions')) errors.push('legacy formation-actions footer still used'); return errors.length ? fail(errors) : ok(); }
export async function verifyApplyButtonIsInSideRailNotOverlayFooter() { const css = await readText('../../css/style.css'); const errors = []; if (!css.includes('grid-template-columns:minmax(0,1fr) clamp(210px,22vw,320px)')) errors.push('formation panel not side rail grid'); if (!css.includes('.formation-action-rail{')) errors.push('formation-action-rail css missing'); if (css.includes('position:sticky;bottom:0') || css.includes('.formation-actions')) errors.push('sticky footer style detected'); return errors.length ? fail(errors) : ok(); }
export async function verifyApplyClickCallsOnApplyBattle() { const src = await readText('./FormationEditor.js'); const errors = []; if (!src.includes("action = e.target.closest('[data-action]')")) errors.push('action lookup missing'); if (!src.includes("type === 'apply'")) errors.push('apply branch missing'); if (!src.includes('e.preventDefault()') || !src.includes('e.stopPropagation()')) errors.push('apply missing preventDefault/stopPropagation'); if (!src.includes('await this.onApplyBattle(this.formation)')) errors.push('onApplyBattle await missing'); if (!src.includes('btn.disabled = true') || !src.includes('btn.disabled = false')) errors.push('button disable/enable flow missing'); if (!src.includes('this.applying = true') || !src.includes('this.applying = false')) errors.push('applying state flow missing'); return errors.length ? fail(errors) : ok(); }
export async function verifyPreviewAppApplyPathStartsBattle() { const src = PreviewApp.prototype.applyFormationToBattle.toString(); const errors = []; if (!src.includes('resetBattle')) errors.push('apply path missing resetBattle call'); if (!src.includes('formationEditor?.setVisible(false)')) errors.push('apply path missing formation hide'); if (!src.includes('productionBar?.setVisible(true)')) errors.push('apply path missing production visible'); if (!src.includes('sceneReady = true')) errors.push('apply path missing scene ready'); return errors.length ? fail(errors) : ok(); }
export async function verifyDevPanelsHiddenByDefault() { const html = await readText('../../index.html'); const css = await readText('../../css/style.css'); const errors = []; if (!html.includes('id="control-panel"') || !html.includes('hidden')) errors.push('control panel hidden missing'); if (!html.includes('id="log-panel"') || !html.includes('hidden')) errors.push('log panel hidden missing'); if (!css.includes('.control-panel,.log-panel{display:none}')) errors.push('dev panels default hidden css missing'); if (!css.includes('body.debug-ui-enabled .control-panel,body.debug-ui-enabled .log-panel{display:block}')) errors.push('debug-ui-enabled display rule missing'); return errors.length ? fail(errors) : ok(); }
export async function verifyPreviewUiNoopWhenHidden() { const src = await readText('../preview/PreviewUi.js'); const errors = []; if (!src.includes('this.enabled = !!(root && !root.hidden)')) errors.push('hidden-root noop gate missing'); if (!src.includes('if (!this.enabled || !this.root) return;')) errors.push('init no-op guard missing'); if (src.includes('Formation Battle Controls') || src.includes("id='reset-battle'") || src.includes("<label>Speed</label>") || src.includes("<strong>Debug</strong>")) errors.push('legacy preview controls still present'); return errors.length ? fail(errors) : ok(); }
export async function verifyFormationOverlayOwnsPointerEvents() { const css = await readText('../../css/style.css'); const errors = []; if (!css.includes('.formation-ui{position:absolute;inset:0;z-index:30;pointer-events:auto')) errors.push('formation-ui pointer events or z-index missing'); if (!css.includes('.formation-action-rail') || !css.includes('pointer-events:auto')) errors.push('action rail pointer events missing'); if (!css.includes('.apply-battle-button{pointer-events:auto')) errors.push('apply button pointer events missing'); return errors.length ? fail(errors) : ok(); }
export async function verifyCriticalCssSelectorsAreNotDuplicated() { const css = await readText('../../css/style.css'); const errors = []; for (const sel of ['.formation-catalog-scroll', '.prod-ui .cards']) { if (defs(css, sel) > 1) errors.push(`duplicate ${sel}`); } if (defs(css, '.formation-panel') > 2) errors.push('duplicate .formation-panel'); if (defs(css, '.formation-action-rail') > 2) errors.push('duplicate .formation-action-rail'); const block = css.split('.formation-panel{')[1]?.split('}')[0] || ''; if (block.includes('display:grid') && block.includes('display:flex')) errors.push('formation-panel has both grid and flex'); return errors.length ? fail(errors) : ok(); }
