const readText = async (rel) => { const mod = await import('node' + ':fs' + '/promises'); return mod.readFile(new URL(rel, import.meta.url), 'utf8'); };

const ok = (details = null) => ({ ok: true, errors: [], details });
const fail = (errors, details = null) => ({ ok: false, errors, details });
const cssDefs = (css, selector) => (css.match(new RegExp(`${selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*\\{`, 'g')) || []).length;

export async function verifyIndexUsesFullscreenGameShell() { const html = await readText('../../index.html'); const errors = []; if (!html.includes('app-shell game-shell')) errors.push('missing game-shell'); if (!html.includes('canvas-panel')) errors.push('missing canvas-panel'); if (!html.includes('id="control-panel"') || !html.includes('hidden')) errors.push('control-panel not hidden by default'); if (!html.includes('id="log-panel"') || !html.includes('hidden')) errors.push('log-panel not hidden by default'); return errors.length ? fail(errors) : ok(); }
export async function verifyControlAndLogPanelsAreHiddenByDefault() { const css = await readText('../../css/style.css'); const errors = []; if (!css.includes('.dev-panel[hidden]') || !css.includes('display:none')) errors.push('hidden dev panel CSS missing'); if (!css.includes('.dev-log[hidden]')) errors.push('hidden dev log CSS missing'); return errors.length ? fail(errors) : ok(); }
export async function verifyApplyBattleButtonIsAlwaysInFormationFooter() { const src = await readText('./FormationEditor.js'); const errors = []; if (!src.includes("data-action='apply'")) errors.push('apply action missing'); if (!src.includes('apply-battle-button')) errors.push('apply button class missing'); if (!src.includes('formation-actions')) errors.push('formation-actions footer missing'); if (!src.includes('Apply Battle')) errors.push('apply text missing'); return errors.length ? fail(errors) : ok(); }
export async function verifyFormationLayoutKeepsActionsVisible() { const css = await readText('../../css/style.css'); const errors = []; if (!css.includes('grid-template-rows:auto auto minmax(0,1fr) auto')) errors.push('formation panel rows invalid'); if (!css.includes('.formation-actions{position:sticky')) errors.push('formation actions not sticky'); if (!css.includes('.formation-catalog-scroll{min-height:0;overflow-y:auto')) errors.push('catalog scroll overflow missing'); return errors.length ? fail(errors) : ok(); }
export async function verifyPreviewUiCanRunNoopWhenHidden() { const src = await readText('../preview/PreviewUi.js'); const errors = []; for (const token of ['this.enabled', 'if (!this.enabled || !this.root) return;', 'if (!this.logEl || this.logEl.hidden)']) if (!src.includes(token)) errors.push(`missing ${token}`); return errors.length ? fail(errors) : ok(); }
export async function verifyResetBattleIsNotInitialStartControl() { const src = await readText('../preview/PreviewApp.js'); const errors = []; if (!src.includes('onApplyBattle: async ()=>{ await this.applyFormationToBattle(); }')) errors.push('apply pathway missing'); if (!src.includes('debugUi')) errors.push('debug ui gating missing'); return errors.length ? fail(errors) : ok(); }
export async function verifyCssHasNoSidePanelLayoutInDefaultMode() { const css = await readText('../../css/style.css'); const errors = []; if (css.includes('.main-area{display:flex')) errors.push('main-area flex remains'); if (css.includes('.control-panel{width:320px')) errors.push('control panel 320 remains'); if (css.includes('.log-panel{height:180px')) errors.push('log panel 180 remains'); return errors.length ? fail(errors) : ok(); }
export async function verifyNoDuplicateCriticalCssSelectors() { const css = await readText('../../css/style.css'); const errors = []; if (cssDefs(css, '.formation-panel') > 1) errors.push('duplicate .formation-panel'); if (cssDefs(css, '.prod-ui .cards') > 1) errors.push('duplicate .prod-ui .cards'); if (cssDefs(css, '.formation-catalog-scroll') > 1) errors.push('duplicate .formation-catalog-scroll'); return errors.length ? fail(errors) : ok(); }
