import { BATTLE_CONFIG } from '../battle/BattleConfig.js';
import { LINEUP_COLS } from '../battle/FormationStore.js';
import { BcuImgCut } from './BcuImgCut.js';
import { BcuSpriteText } from './BcuSpriteText.js';

const CARD = { w: 128, h: 128 };
const UNI_PNG = './public/assets/bcu/000001/org/page/uni.png';
const UNI_IMGCUT = './public/assets/bcu/000001/org/data/uni.imgcut';

const loadImage = (src) => new Promise((res, rej) => { const i = new Image(); i.onload = () => res(i); i.onerror = () => rej(new Error(`image load failed:${src}`)); i.src = src; });

export function getCardStackRenderModel(scene, col) { const rows = scene?.getPlayerLineupRows?.() || [[], []]; const front = scene?.frontLineup ?? 0; const back = front === 0 ? 1 : 0; return { col, back: { unitDef: rows[back]?.[col] || null, interactive: false, row: back }, front: { unitDef: rows[front]?.[col] || null, interactive: !!rows[front]?.[col] && !scene?.lineupChanging, row: front } }; }
export function getLineupRenderModel(scene) { return Array.from({ length: LINEUP_COLS }, (_, col) => getCardStackRenderModel(scene, col)); }

export class PlayerProductionBar {
  constructor({ scene, mount = document.body }) { this.scene = scene; this.mount = mount; this.cardStacks = []; this.iconCache = new Map(); this.spriteText = new BcuSpriteText(); this.setup(); this.initAssets(); }
  async initAssets() { this.spriteText.init?.(); try { this.uniImg = await loadImage(UNI_PNG); this.uniCut = await BcuImgCut.load(UNI_IMGCUT); } catch (_e) {} }
  setVisible(v) { this.root?.classList.toggle('is-hidden', !v); }
  setup() { this.root = document.createElement('div'); this.root.className = 'prod-ui is-hidden'; this.root.innerHTML = "<canvas class='battle-money' width='360' height='48'></canvas><div class='cards lineup-cards'></div>"; this.mount.appendChild(this.root); this.cardsWrap = this.root.querySelector('.cards'); this.moneyCanvas = this.root.querySelector('.battle-money'); this.moneyCtx = this.moneyCanvas.getContext('2d'); this.rebuildStacks(); this.cardsWrap.addEventListener('pointerup', (e) => { const t = e.target.closest('.prod-card.is-front[data-col]'); if (!t || this.scene?.lineupChanging) return; const col = Number(t.dataset.col); const model = getCardStackRenderModel(this.scene, col); if (!model.front.interactive) return; this.scene?.requestPlayerSpawn?.(null, model.front.row, col); }); }
  rebuildStacks() { this.cardsWrap.innerHTML = ''; this.cardStacks = []; for (let col = 0; col < LINEUP_COLS; col += 1) { const stackEl = document.createElement('div'); stackEl.className = 'prod-card-stack'; stackEl.dataset.col = String(col); const backCanvas = document.createElement('canvas'); backCanvas.className = 'prod-card is-back'; backCanvas.width = CARD.w; backCanvas.height = CARD.h; const frontCanvas = document.createElement('canvas'); frontCanvas.className = 'prod-card is-front'; frontCanvas.dataset.col = String(col); frontCanvas.width = CARD.w; frontCanvas.height = CARD.h; stackEl.append(backCanvas, frontCanvas); this.cardsWrap.appendChild(stackEl); this.cardStacks.push({ col, stackEl, backCanvas, frontCanvas, backCtx: backCanvas.getContext('2d'), frontCtx: frontCanvas.getContext('2d') }); } }
  async ensureCardAssets(unitDef) { if (!unitDef?.uiIcon) return null; const key = unitDef.characterId || unitDef.slotId || unitDef.assetId; if (this.iconCache.has(key)) return this.iconCache.get(key); const p = (async () => { try { return await loadImage(unitDef.uiIcon.primary); } catch (_e) { if (unitDef.uiIcon.fallback) return loadImage(unitDef.uiIcon.fallback).catch(() => null); return null; } })(); this.iconCache.set(key, p); return p; }
  drawEmptyCard(ctx) { ctx.clearRect(0, 0, CARD.w, CARD.h); ctx.strokeStyle = 'rgba(255,255,255,0.2)'; ctx.strokeRect(8, 8, CARD.w - 16, CARD.h - 16); }
  drawCooldownBar(ctx, ratio) { if (!(ratio > 0)) return; ctx.fillStyle = 'rgba(0,0,0,.45)'; ctx.fillRect(6, CARD.h - 12, (CARD.w - 12) * Math.max(0, Math.min(1, ratio)), 6); }
  drawCard(ctx, entry, isBack = false) { ctx.clearRect(0, 0, CARD.w, CARD.h); if (!entry?.unitDef) return this.drawEmptyCard(ctx); if (this.uniImg && this.uniCut?.parts?.[0]) this.uniCut.draw(ctx, this.uniImg, this.uniCut.parts[0], 0, 0, CARD.w, CARD.h); const icon = entry.icon; if (icon) ctx.drawImage(icon, 20, 20, 88, 72); const cost = Number(entry.unitDef.cost || 0); this.spriteText.drawCostRight(ctx, cost, CARD.w - 8, CARD.h - 18, { disabled: !entry.interactive, scale: 0.8 }); if (isBack) { ctx.fillStyle = 'rgba(0,0,0,.2)'; ctx.fillRect(0, 0, CARD.w, CARD.h); } this.drawCooldownBar(ctx, entry.cooldownRatio || 0); if (!entry.interactive) { ctx.fillStyle = 'rgba(0,0,0,.25)'; ctx.fillRect(0, 0, CARD.w, CARD.h); } }
  async update(scene = this.scene) { this.scene = scene; if (!scene) return; const model = getLineupRenderModel(scene); for (const stack of this.cardStacks) { const m = model[stack.col]; const backEntry = { ...m.back, icon: await this.ensureCardAssets(m.back.unitDef), interactive: false }; const frontEntry = { ...m.front, icon: await this.ensureCardAssets(m.front.unitDef) }; this.drawCard(stack.backCtx, backEntry, true); this.drawCard(stack.frontCtx, frontEntry, false); stack.frontCanvas.classList.toggle('is-disabled', !frontEntry.interactive); } }
}
