import { PRODUCTION_CARD_SKIN } from './ProductionCardSkin.js';
import { BattleEconomy } from '../battle/BattleEconomy.js';

const ok = (details = null) => ({ ok: true, errors: [], details });
const ng = (...errors) => ({ ok: false, errors, details: null });
const read = async (p, enc='utf8') => (await import('node:fs/promises')).readFile(new URL(`../../${p}`, import.meta.url), enc);

function parsePngSize(buf){ return { w: buf.readUInt32BE(16), h: buf.readUInt32BE(20) }; }
export async function verifyRepresentativeCatPngNaturalSize(){ const b=await read('public/assets/bcu/000004/org/unit/000/f/uni000_f00.png',null); const {w,h}=parsePngSize(b); return (w>0&&h>0)?ok({w,h}):ng('cat png size read failed'); }
export async function verifyCatDrawUsesNineArgsAndNoStretch(){ const s=await read('js/ui/ProductionCardSkin.js'); const errs=[]; if(!/drawImage\(icon,\s*s\.x,\s*s\.y,\s*s\.w,\s*s\.h,\s*0,\s*0,\s*s\.w,\s*s\.h\)/.test(s)) errs.push('cat drawImage 9-arg ratio-preserving draw missing'); if(/drawImage\(icon,\s*0,\s*0,\s*PRODUCTION_CARD_CANVAS\.w,\s*PRODUCTION_CARD_CANVAS\.h\)/.test(s)) errs.push('forbidden stretched cat draw found'); return errs.length?ng(...errs):ok(); }
export async function verifyGeometrySharedForDogCatEmpty(){ const s=await read('js/ui/ProductionCardSkin.js'); const errs=[]; if(!/drawEmptyCard\(ctx\) \{ this\.drawDogCard\(ctx, null\); \}/.test(s)) errs.push('empty card not shared with dog geometry'); if(!/const r = g\.contentRect/.test(s)) errs.push('dog contentRect not geometry-driven'); if(!/costRightX:/.test(s)||!/costBaselineY:/.test(s)) errs.push('cost geometry missing'); return errs.length?ng(...errs):ok(); }
export async function verifyCooldownProgressFlow(){ const econ = new BattleEconomy({ startMoney: 9999 }); const unit={ slotId:'u', cost:10, cooldownMs:3000 }; econ.produce(unit); const s1=econ.getStatus(unit); econ.tick(1500); const s2=econ.getStatus(unit); econ.tick(1500); const s3=econ.getStatus(unit); const barW = PRODUCTION_CARD_SKIN.cooldownBarRect.w; const w1=Math.floor(barW*s1.cooldownProgressRatio), w2=Math.floor(barW*s2.cooldownProgressRatio), w3=Math.floor(barW*s3.cooldownProgressRatio); const errs=[]; if(s1.cooldownRemainingRatio!==1||s1.cooldownProgressRatio!==0||w1!==0) errs.push('cooldown case 3000ms failed'); if(Math.abs(s2.cooldownRemainingRatio-0.5)>1e-9||Math.abs(s2.cooldownProgressRatio-0.5)>1e-9||w2!==Math.floor(barW*0.5)) errs.push('cooldown case 1500ms failed'); if(s3.cooldownRemainingRatio!==0||s3.cooldownProgressRatio!==1||w3!==barW) errs.push('cooldown case 0ms failed'); return errs.length?ng(...errs):ok({w1,w2,w3,barW}); }
export async function verifyPlayerBarPassesProgressRatio(){ const s=await read('js/ui/PlayerProductionBar.js'); const errs=[]; if(!/cooldownProgressRatio: backStatus\?\.cooldownProgressRatio \?\? 1/.test(s)) errs.push('back row cooldownProgressRatio feed missing'); if(!/cooldownProgressRatio: frontStatus\?\.cooldownProgressRatio \?\? 1/.test(s)) errs.push('front row cooldownProgressRatio feed missing'); if(/cooldownRatio:\s*entry\./.test(s)) errs.push('legacy cooldownRatio still passed to skin'); return errs.length?ng(...errs):ok(); }
export async function runProductionCardSkinVerifier(){ const checks=[verifyRepresentativeCatPngNaturalSize,verifyCatDrawUsesNineArgsAndNoStretch,verifyGeometrySharedForDogCatEmpty,verifyCooldownProgressFlow,verifyPlayerBarPassesProgressRatio]; const results=await Promise.all(checks.map(async(fn)=>({name:fn.name,...await fn()}))); const failed=results.filter(r=>!r.ok); return {ok:failed.length===0,results,failed}; }
