import { BattleAttackProfile } from './BattleAttackProfile.js';

export class BattleAttackResolver {
  static getEntityPosBcu(entity){ if(typeof entity?.getBattlePosBcu==='function') return entity.getBattlePosBcu(); return Number.isFinite(entity?.posBcu)?entity.posBcu:null; }
  static getAttackIntervalBcu(actor,event){ const pos=this.getEntityPosBcu(actor); if(!Number.isFinite(pos)) return null; const dir=Number.isFinite(actor?.direction)?actor.direction:1; const kind=event?.attackKind||'normal'; let p0,p1; if(kind==='ld'||kind==='omni'){ p0=pos+dir*(event?.shortPointBcu??0); p1=pos+dir*(event?.longPointBcu??0);} else { p0=pos+dir*(event?.rangeEndBcu??actor?.detectionRangeBcu??0); p1=pos-dir*(event?.attackBackBcu??actor?.attackWidthBcu??0);} return {leftBcu:Math.min(p0,p1),rightBcu:Math.max(p0,p1),kind,posBcu:pos}; }
  static getTouchIntervalBcu(actor){ return this.getAttackIntervalBcu(actor,{attackKind:'normal',rangeEndBcu:actor?.detectionRangeBcu??0,attackBackBcu:actor?.attackWidthBcu??0}); }
  static isTargetPosInIntervalBcu(target,interval){ const p=this.getEntityPosBcu(target); if(!Number.isFinite(p)||!interval) return false; return p>=interval.leftBcu&&p<=interval.rightBcu; }
  static isTargetTouchable(attacker,target){ return this.isTargetPosInIntervalBcu(target,this.getTouchIntervalBcu(attacker)); }
  static isTargetInEventRange(attacker,target,event){ return this.isTargetPosInIntervalBcu(target,this.getAttackIntervalBcu(attacker,event)); }
  static chooseSingleTarget(attacker,candidates){ const dir=Number.isFinite(attacker?.direction)?attacker.direction:1; const ap=this.getEntityPosBcu(attacker)??0; return (candidates||[]).slice().sort((a,b)=>{ const ax=this.getEntityPosBcu(a.target)??0; const bx=this.getEntityPosBcu(b.target)??0; const f=dir>0?(ax-bx):(bx-ax); if(f!==0)return f; return Math.abs(ax-ap)-Math.abs(bx-ap); })[0]||null; }
  static captureTargets({attacker,enemyActors,enemyBase,event}){ const mode=event?.targetMode||'single'; const actorCandidates=(enemyActors||[]).filter(t=>t?.isAlive?.()).filter(t=>this.isTargetInEventRange(attacker,t,event)).map(target=>({target,targetType:'actor',event})); const baseCandidate=enemyBase?.isAlive?.()&&event?.allowBaseHit!==false&&this.isTargetInEventRange(attacker,enemyBase,event)?{target:enemyBase,targetType:'base',event}:null; if(mode==='range'){ const r=[...actorCandidates]; if(baseCandidate)r.push(baseCandidate); return r; } const c=actorCandidates.length?actorCandidates:(baseCandidate?[baseCandidate]:[]); const one=this.chooseSingleTarget(attacker,c); return one?[one]:[]; }
  static getAttackInterval(actor,event){ const bcu=this.getAttackIntervalBcu(actor,event||BattleAttackProfile.ensure(actor)?.events?.[0]); if(!bcu)return null; const coord=actor?.battleCoordinate; const left=coord?coord.toScreenX(bcu.leftBcu):(actor?.x||0); const right=coord?coord.toScreenX(bcu.rightBcu):(actor?.x||0); return {...bcu,left,right,startX:left,endX:right}; }
  static getAttackDebugLine(actor,event){ return this.getAttackInterval(actor,event); }
}
