import { BattleBase } from './BattleBase.js';
import { BattleActorFactory } from './BattleActorFactory.js';
import { BattleStatsLoader } from './BattleStatsLoader.js';
import { BattleEconomy } from './BattleEconomy.js';
import { BATTLE_CONFIG } from './BattleConfig.js';
import { BattleEffect } from './BattleEffect.js';
import { BattleEffectLoader } from './BattleEffectLoader.js';
import { StageBackgroundLoader } from './StageBackgroundLoader.js';
import { PREVIEW_ASSETS } from '../data/previewAssets.js';
import { BattleBodyResolver } from './BattleBodyResolver.js';
import { BattleAttackProfile } from './BattleAttackProfile.js';
import { BattleAttackResolver } from './BattleAttackResolver.js';
import { BattleCoordinate } from './BattleCoordinate.js';

export class BattleScene {
  constructor(uiLog){this.log=uiLog||(()=>{});this.bgLoader=new StageBackgroundLoader(uiLog);this.statsLoader=new BattleStatsLoader();this.coordinate=new BattleCoordinate(BATTLE_CONFIG.battleCoordinate,BATTLE_CONFIG.bases,BATTLE_CONFIG.tuning);this.actorFactory=new BattleActorFactory(this.statsLoader,BATTLE_CONFIG.tuning,this.coordinate);this.actors=[];this.bases=[];this.actorSerial=0;this.battleState='running';this.timeMs=0;this.debugEvents=[];this.enemySpawnerState=[];this.economy=null;this.effects=[];this.effectLoader=new BattleEffectLoader();this.hitEffectAsset=null;this.groundY=BATTLE_CONFIG.visualLayout?.groundY??BATTLE_CONFIG.groundY;this.actorGroundY=BATTLE_CONFIG.visualLayout?.actorGroundY??this.groundY;this.stage={...BATTLE_CONFIG.stage,background:null,backgroundLoadFailed:false};}
  findAsset(id){return PREVIEW_ASSETS.find(a=>a.id===id)}
  async loadCompositeLayers(asset){const loaded=[];for(const l of (asset.layers||[])){try{const i=new Image();await new Promise((res,rej)=>{i.onload=res;i.onerror=rej;i.src=`${l.baseDir}${l.image}`});loaded.push({id:l.id,offsetX:l.offsetX||0,offsetY:l.offsetY||0,image:i});}catch{}}return loaded;}
  async loadBase(def){const b=new BattleBase(def);if(def.visualKind==='castle-composite'&&def.visualAssetId){const a=this.findAsset(def.visualAssetId);if(a)b.layers=await this.loadCompositeLayers(a);}return b;}
  async preloadRosters(){for(const u of BATTLE_CONFIG.rosters.dogPlayer) await this.actorFactory.preloadTemplate(u); for(const u of BATTLE_CONFIG.rosters.catEnemy) await this.actorFactory.preloadTemplate(u);}
  nextInstanceId(side,unitId){this.actorSerial+=1;const p=side==='dog-player'?'dog':'cat';return `${p}-${unitId.replace(/\D/g,'')||'000'}-${this.actorSerial}`;}
  getDepthLaneForSpawn(){const depth=BATTLE_CONFIG.visualLayout?.actorDepth;const laneCount=Math.max(1,Math.floor(depth?.laneCount??1));if(!depth?.enabled||laneCount<=1)return{laneIndex:0,laneCount:1,yOffset:0,scaleMultiplier:1};const laneIndex=depth.randomizeOnSpawn?Math.floor(Math.random()*laneCount):Math.floor(laneCount/2);const t=laneCount<=1?0:laneIndex/(laneCount-1);const minY=Number.isFinite(depth.minYOffset)?depth.minYOffset:0;const maxY=Number.isFinite(depth.maxYOffset)?depth.maxYOffset:0;const minScale=Number.isFinite(depth.minScaleMultiplier)?depth.minScaleMultiplier:1;const maxScale=Number.isFinite(depth.maxScaleMultiplier)?depth.maxScaleMultiplier:1;return{laneIndex,laneCount,yOffset:minY+(maxY-minY)*t,scaleMultiplier:minScale+(maxScale-minScale)*t};}
  applyVisualDepth(actor,unitDef){const lane=this.getDepthLaneForSpawn();const baseScale=unitDef.scale??1;const globalScale=BATTLE_CONFIG.visualLayout?.actorGlobalScale??1;const laneScale=lane.scaleMultiplier??1;actor.visualDepthLaneIndex=lane.laneIndex;actor.visualDepthLaneCount=lane.laneCount;actor.visualDepthYOffset=lane.yOffset;actor.visualBaseScale=baseScale;actor.visualGlobalScale=globalScale;actor.visualDepthScaleMultiplier=laneScale;actor.y=this.actorGroundY+lane.yOffset;actor.scale=baseScale*globalScale*laneScale;}
  spawnActor(unitDef, side, isPlayerProduced=false){const base=this.bases.find(b=>b.side===side); if(!base)return null; const pos0=this.coordinate.getSpawnPosBcu(side); const same=this.actors.filter(a=>a.side===side&&a.isAlive()); const sep=this.coordinate.sameSideSeparationBcu||140; const dir=this.coordinate.getDirectionForSide(side); const posBcu=pos0+dir*sep*same.length; const actor=this.actorFactory.createActor(unitDef.slotId,{side,posBcu,x:this.coordinate.toScreenX(posBcu),y:this.actorGroundY,direction:unitDef.direction,facing:unitDef.facing,renderFlipX:unitDef.renderFlipX,scale:unitDef.scale,currentAnimId:unitDef.moveAnimId,battleCoordinate:this.coordinate}); this.applyVisualDepth(actor,unitDef); actor.setPosBcu(posBcu,this.coordinate); actor.applyCurrentAnimationFrame(); actor.initializeCombatBodyFrontFromModel?.(); actor.instanceId=this.nextInstanceId(side,unitDef.assetId); actor.spawnedAtMs=this.timeMs; actor.removeAfterMs=1000; actor.slotId=unitDef.slotId; actor.isPlayerProduced=isPlayerProduced; actor.label=unitDef.label; this.actors.push(actor); return actor;}
  requestPlayerSpawn(slotId){const def=BATTLE_CONFIG.rosters.dogPlayer.find(x=>x.slotId===slotId); if(!def||!this.economy.produce(def)) return false; this.spawnActor(def,'dog-player',true); return true;}
  spawnEnemy(slotId){const def=BATTLE_CONFIG.rosters.catEnemy.find(x=>x.slotId===slotId); if(!def)return false; const alive=this.actors.filter(a=>a.isAlive()&&a.side==='cat-enemy').length; if(alive>=BATTLE_CONFIG.tuning.maxAliveActorsPerSide)return false; this.spawnActor(def,'cat-enemy',false); return true;}
  getPlayerRosterStatus(){return BATTLE_CONFIG.rosters.dogPlayer.map(u=>({slotId:u.slotId,label:u.label,cost:u.cost,...this.economy.getStatus(u)}));}
  findEnemyActors(actor){return this.actors.filter(a=>a.side!==actor.side&&a.isAlive());}
  findEnemyBase(actor){return this.bases.find(b=>b.side!==actor.side&&b.isAlive());}
  findTargetForActor(actor){const es=this.findEnemyActors(actor); if(es.length){const ap=actor.getBattlePosBcu?.()??0;es.sort((a,b)=>{const ax=a.getBattlePosBcu?.()??0;const bx=b.getBattlePosBcu?.()??0;const front=actor.direction>0?(ax-bx):(bx-ax);if(front!==0)return front;return Math.abs(ax-ap)-Math.abs(bx-ap);});if(this.canAttack(actor,es[0]))return {target:es[0],targetType:'actor'};} const b=this.findEnemyBase(actor); return b&&this.canAttack(actor,b)?{target:b,targetType:'base'}:null;}
  canAttack(a,t){return BattleAttackResolver.isTargetTouchable(a,t);}
  isTargetAliveForAttack(target,targetType){if(!target)return false;if(targetType==='actor')return typeof target.isAlive==='function'?target.isAlive():false;if(targetType==='base')return typeof target.isAlive==='function'?target.isAlive():(!target.destroyed&&target.hp>0);return false;}
  getEffectiveAttackStartupMs(actor){const minStartup=BATTLE_CONFIG.tuning.minAttackStartupMs??0;return Math.max(actor.attackStartupMs||0,minStartup);}
  getAttackProfile(actor){return actor.getAttackProfile?.()||BattleAttackProfile.ensure(actor);}
  getAttackEndMs(actor){return BattleAttackProfile.getAttackEndMs(actor);}
  captureHitTargets(attacker,event){const enemyActors=this.findEnemyActors(attacker);const enemyBase=this.findEnemyBase(attacker);return BattleAttackResolver.captureTargets({attacker,enemyActors,enemyBase,event});}

  getStatsSourceReport(){
    const templates=[...this.actorFactory.templates.entries()].map(([slotId,tpl])=>({slotId,label:tpl.unitDef?.label,assetId:tpl.unitDef?.assetId,statsType:tpl.unitDef?.statsType,configuredSide:tpl.unitDef?.side,bcuAssetKind:tpl.stats?.source?.bcuAssetKind||tpl.unitDef?.statsType,bcuRole:tpl.stats?.source?.bcuRole||'-',sourceFile:tpl.stats?.source?.file||'-',sourceRow:Number.isFinite(tpl.stats?.source?.row)?tpl.stats.source.row:null,mapping:tpl.stats?.source?.mapping||'-',mappingStatus:tpl.stats?.source?.mappingStatus||'-',hp:tpl.stats?.hp,damage:tpl.stats?.damage,speed:tpl.stats?.speed,range:tpl.stats?.range??tpl.stats?.detectionRange,width:tpl.stats?.width,attackCount:tpl.stats?.attackCount}));
    const actors=this.actors.map((actor)=>({instanceId:actor.instanceId,slotId:actor.slotId,label:actor.label,side:actor.side,assetId:actor.unitId,statsType:actor.statSource?.statsType,bcuAssetKind:actor.statSource?.bcuAssetKind,bcuRole:actor.statSource?.bcuRole,sourceFile:actor.statSource?.file,sourceRow:Number.isFinite(actor.statSource?.row)?actor.statSource.row:null,hp:actor.hp,maxHp:actor.maxHp,damage:actor.damage,moveSpeed:actor.moveSpeed,detectionRangePx:actor.detectionRangePx,attackEvents:Array.isArray(actor.attackProfile?.events)?actor.attackProfile.events.length:null}));
    return {templates,actors};
  }

  startActorAttack(actor,target,targetType){actor.attackTarget=target;actor.attackTargetType=targetType;actor.attackStartedAtMs=this.timeMs;actor.setState('attack');actor.setAnimation(actor.attackAnimId,'attack',true);actor.applyCurrentAnimationFrame();}
  tickKnockback(actor,dt,target){actor.knockbackPositionElapsedMs+=dt; const t=Math.min(1,actor.knockbackPositionElapsedMs/Math.max(1,actor.knockbackPositionDurationMs)); const ease=t*(2-t); actor.posBcu=actor.knockbackFromPosBcu+(actor.knockbackToPosBcu-actor.knockbackFromPosBcu)*ease;actor.syncScreenFromBcu(this.coordinate); if(t>=1){ if(actor.deathAfterKnockback||actor.hp<=0||actor.deathPending){const wasDead=actor.state==='dead';actor.enterDeadState?.(this.timeMs);actor.deathAfterKnockback=false;actor.applyCurrentAnimationFrame?.();if(!wasDead){this.pushEvent?.({type:'dead',actor:actor.instanceId||actor.label,timeMs:this.timeMs});}return;} if(actor.isAlive()&&target&&this.canAttack(actor,target)){actor.setState('attack-wait');actor.setAnimation(actor.idleAnimId,'attack-wait',true);} else {actor.setState('move');actor.setAnimation(actor.moveAnimId,'move',true);} actor.applyCurrentAnimationFrame(); }}
  resolveSameSideSpacing(){for(const side of ['dog-player','cat-enemy']){const arr=this.actors.filter(a=>a.side===side&&a.isAlive()).sort((a,b)=>a.x-b.x); for(let i=1;i<arr.length;i++){const prev=arr[i-1],cur=arr[i];const min=BATTLE_CONFIG.tuning.spawnSeparationPx; if(Math.abs(cur.x-prev.x)<min) cur.x=prev.x+min;}}}
  cleanupDead(){this.actors=this.actors.filter((actor)=>{if(actor.isAlive?.())return true;if(actor.isFinalKnockback?.())return true;if(actor.state==='knockback'&&(actor.deathAfterKnockback||actor.deathPending||actor.hp<=0))return true;if(actor.isRenderable?.()&&!actor.isRemovable?.(this.timeMs))return true;return false;});}
  tickEffects(dt){for(const e of this.effects)e.tick(dt);}
  cleanupEffects(){this.effects=this.effects.filter(e=>!e.finished);}

  getCombatBodyBoxForTarget(target){return BattleBodyResolver.getCombatBodyBox(target);}
  getHitEffectPosition(attacker,target,targetType){return BattleBodyResolver.getHitEffectPosition(attacker,target);}
  spawnHitEffect(attacker,target,targetType){if(!this.hitEffectAsset?.parts?.length)return; const scale=targetType==='base'?1.2:1.0; const {x,y}=this.getHitEffectPosition(attacker,target,targetType); if(this.effects.length>=BATTLE_CONFIG.tuning.maxEffects)return; this.effects.push(new BattleEffect({id:`fx-${this.timeMs}-${Math.random()}`,x,y,frameParts:this.hitEffectAsset.parts,image:this.hitEffectAsset.image,scale}));}
  updateBattleState(){const dog=this.bases.find(b=>b.side==='dog-player');const cat=this.bases.find(b=>b.side==='cat-enemy');if(dog.destroyed&&cat.destroyed)this.battleState='draw'; else if(dog.destroyed)this.battleState='cat-win'; else if(cat.destroyed)this.battleState='dog-win'; else this.battleState='running';}
  async init(){this.actors=[];this.bases=[];this.actorSerial=0;this.timeMs=0;this.debugEvents=[];this.battleState='running';this.economy=new BattleEconomy(BATTLE_CONFIG.economy.dogPlayer);this.enemySpawnerState=BATTLE_CONFIG.enemySpawnSchedule.map((s)=>({...s,nextAtMs:s.atMs})); this.stage={...BATTLE_CONFIG.stage,background:null,backgroundLoadFailed:false}; try{this.stage.background=await this.bgLoader.load(BATTLE_CONFIG.stage);}catch{this.stage.backgroundLoadFailed=true;} await this.preloadRosters(); try{this.hitEffectAsset=await this.effectLoader.loadHitEffect();}catch{this.hitEffectAsset=null;} this.bases=[await this.loadBase(BATTLE_CONFIG.bases.dogBase),await this.loadBase(BATTLE_CONFIG.bases.catBase)];this.bases.forEach((b)=>b.applyCoordinate?.(this.coordinate)); this.spawnActor(BATTLE_CONFIG.rosters.dogPlayer[0],'dog-player',true); this.spawnActor(BATTLE_CONFIG.rosters.catEnemy[0],'cat-enemy',false);}
  tick(dt){if(this.battleState!=='running')return;const e=dt*BATTLE_CONFIG.tuning.battleTimeScale;this.timeMs+=e;this.economy.tick(e); for(const s of this.enemySpawnerState){if(this.timeMs>=s.nextAtMs){this.spawnEnemy(s.slotId); if(s.repeatMs)s.nextAtMs+=s.repeatMs; else s.nextAtMs=Infinity;}}
    const queue=[]; for(const a of this.actors){if(a.needsLifecycleTick?!a.needsLifecycleTick():!a.isAlive())continue; a.tick(e); if(a.state==='dead'){continue;} if(a.state==='knockback'){ const kbTarget=a.attackTarget&&this.isTargetAliveForAttack(a.attackTarget,a.attackTargetType)?a.attackTarget:null; this.tickKnockback(a,e,kbTarget); continue; } if(!a.isAlive())continue;
      if(a.state==='attack'){const prev=a.attackElapsedMs;a.attackElapsedMs+=e; const profile=this.getAttackProfile(a); const events=Array.isArray(profile?.events)?profile.events:[]; events.forEach((event,index)=>{const key=BattleAttackProfile.getEventKey(event,index);const atMs=Number.isFinite(event?.atMs)?event.atMs:0; if(a.resolvedAttackEventKeys?.has(key))return; if(!(prev<atMs&&a.attackElapsedMs>=atMs))return; a.resolvedAttackEventKeys.add(key); a.hasHitInCurrentAttack=true; const captured=this.captureHitTargets(a,event); for(const hit of captured){if(!this.isTargetAliveForAttack(hit.target,hit.targetType))continue; queue.push({attacker:a,target:hit.target,targetType:hit.targetType,damage:Number.isFinite(event.damage)?event.damage:a.damage,hitIndex:event.hitIndex??index,attackEventKey:key});}}); const attackEndMs=this.getAttackEndMs(a); if(a.attackElapsedMs>=attackEndMs){a.setState('attack-wait');a.setAnimation(a.idleAnimId,'attack-wait',true);a.applyCurrentAnimationFrame();a.attackTarget=null;a.attackTargetType=null;} continue; }
      const sel=this.findTargetForActor(a);
      if(!sel){a.currentTargetLabel='-';a.currentTargetType='-'; if(a.state==='attack-wait'){a.setState('move');a.setAnimation(a.moveAnimId,'move',true);} if(a.state==='move')a.moveBcu(a.direction*a.moveSpeedBcuPerSecond*(e/1000),this.coordinate); continue;}
      const {target,targetType}=sel; a.currentTargetLabel=target.label;a.currentTargetType=targetType;
      if(a.state==='attack-wait'){a.attackWaitElapsedMs+=e; if(a.attackWaitElapsedMs>=a.nextAttackReadyMs&&this.canAttack(a,target)){this.startActorAttack(a,target,targetType); continue;} if(!this.canAttack(a,target)){a.setState('move');a.setAnimation(a.moveAnimId,'move',true);a.moveBcu(a.direction*a.moveSpeedBcuPerSecond*(e/1000),this.coordinate);} continue;}
      if(!this.canAttack(a,target)){a.setState('move');a.setAnimation(a.moveAnimId,'move');a.moveBcu(a.direction*a.moveSpeedBcuPerSecond*(e/1000),this.coordinate); continue;}
      if(a.state==='move'){this.startActorAttack(a,target,targetType);continue;}
    }
    for(const q of queue){if(!this.isTargetAliveForAttack(q.target,q.targetType))continue; if(q.targetType==='actor'){const result=q.target.takeDamage(q.damage,{attacker:q.attacker,hitIndex:q.hitIndex,attackEventKey:q.attackEventKey,timeMs:this.timeMs}); if(result?.accepted){this.spawnHitEffect(q.attacker,q.target,q.targetType); this.pushEvent?.({type:'damageQueued',actor:q.attacker.instanceId||q.attacker.label,target:q.target.instanceId||q.target.label,targetType:q.targetType,damage:q.damage,timeMs:this.timeMs});} continue;} if(q.targetType==='base'){const result=q.target.takeDamage(q.damage); this.spawnHitEffect(q.attacker,q.target,q.targetType); if(result?.destroyed)this.pushEvent?.({type:'baseDestroyed',target:q.target.label,timeMs:this.timeMs});}} const damageResults=[]; for(const actor of this.actors){const result=actor.resolvePostDamage?.({nowMs:this.timeMs,tuning:BATTLE_CONFIG.tuning}); if(result?.damaged)damageResults.push({actor,result});} for(const {actor,result} of damageResults){if(result.knockedBack){this.pushEvent?.({type:result.deathPending?'finalKnockbackStart':'knockbackStart',actor:actor.instanceId||actor.label,timeMs:this.timeMs,damage:result.damage});} if(result.dead){this.pushEvent?.({type:'dead',actor:actor.instanceId||actor.label,timeMs:this.timeMs});}} this.tickEffects(e); this.cleanupEffects(); this.cleanupDead(); this.updateBattleState();
  }
}
