import { BATTLE_CONFIG } from './BattleConfig.js';

export class BattleSceneRenderer {
  render(previewRenderer, scene, showParts = false) {
    const c = previewRenderer.ctx; const w = previewRenderer.logicalW; const h = previewRenderer.logicalH; const groundY = scene?.groundY || 590;
    c.clearRect(0, 0, w, h);
    if (scene?.stage?.background?.image && scene?.stage?.background?.crop) this.drawBackgroundCropCover(c, scene.stage.background, w, h); else this.drawFallbackBackground(c, w, h, groundY);
    this.drawBases(c, scene?.bases || [], groundY, showParts);
    for (const actor of (scene?.actors || [])) if (actor.isAlive()) this.drawActor(c, actor);
    this.drawEffects(c, scene?.effects || []);
    for (const actor of (scene?.actors || [])) if (actor.isAlive()) this.drawHpBar(c, actor);
    for (const base of (scene?.bases || [])) this.drawBaseHpBar(c, base);
    if (showParts) { for (const actor of (scene?.actors || [])) if (actor.isAlive()) this.drawActorDebug(c, actor, scene?.battleState || 'running'); this.drawEventLog(c, scene?.debugEvents || []); }
    this.drawHud(c, scene, showParts);
  }
  drawBackgroundCropCover(c,bg,w,h){const{image,crop}=bg;const scale=Math.max(w/crop.w,h/crop.h);const dw=crop.w*scale,dh=crop.h*scale;const dx=(w-dw)*0.5,dy=(h-dh)*0.5;c.drawImage(image,crop.x,crop.y,crop.w,crop.h,dx,dy,dw,dh)}
  drawFallbackBackground(c,w,h,groundY){const sky=c.createLinearGradient(0,0,0,groundY);sky.addColorStop(0,'#7dc7ff');sky.addColorStop(1,'#d9f0ff');c.fillStyle=sky;c.fillRect(0,0,w,groundY);c.fillStyle='#c9b78f';c.fillRect(0,groundY,w,h-groundY)}
  drawBases(c,bases,groundY,showParts){for(const base of bases) this.drawBase(c,base,groundY,showParts)}
  drawBase(c,base,groundY,showParts){ if(base.visualKind==='castle-composite'&&base.layers?.length){ for(const layer of base.layers){const s=base.scale||1;const x=base.x+(layer.offsetX||0)*s-layer.image.width*0.5*s;const y=base.y+(layer.offsetY||0)*s-layer.image.height*s;c.drawImage(layer.image,x,y,layer.image.width*s,layer.image.height*s);} } else { c.fillStyle='#374151'; c.fillRect(base.x-50, base.y-80, 100, 80); c.fillStyle='#e5e7eb'; c.fillText('CAT BASE TEMP', base.x-44, base.y-88);} if(showParts) this.drawBaseDebug(c,base); }
  drawBaseHpBar(c,base){const x=base.x-60,y=base.y-210,w=120,h=10;const ratio=Math.max(0,Math.min(1,base.hp/Math.max(1,base.maxHp)));c.fillStyle='#111827';c.fillRect(x,y,w,h);c.fillStyle='#60a5fa';c.fillRect(x,y,w*ratio,h);c.strokeStyle='#e5e7eb';c.strokeRect(x,y,w,h);}
  drawBaseDebug(c,base){c.fillStyle='#0008';c.fillRect(base.x-90,base.y-250,180,34);c.fillStyle='#f8fafc';c.font='12px ui-monospace';c.fillText(`${base.label} hp:${base.hp}/${base.maxHp}`,base.x-84,base.y-230);}
  drawHud(c, scene, showParts) { const dog = scene?.actors?.find((a) => a.side === 'dog-player'); const cat = scene?.actors?.find((a) => a.side === 'cat-enemy'); const dogBase=scene?.bases?.find((b)=>b.side==='dog-player'); const catBase=scene?.bases?.find((b)=>b.side==='cat-enemy'); const aliveDogs=(scene?.actors||[]).filter(a=>a.isAlive()&&a.side==='dog-player').length; const aliveCats=(scene?.actors||[]).filter(a=>a.isAlive()&&a.side==='cat-enemy').length; c.fillStyle = '#0008'; c.fillRect(14, 14, 860, 170); c.fillStyle = '#f8fafc'; c.font = '20px ui-sans-serif'; c.fillText('Wanko Battle v0.7.2', 24, 40); c.font = '14px ui-monospace, monospace'; c.fillText(`dogBase HP:${dogBase?.hp ?? '-'} catBase HP:${catBase?.hp ?? '-'}`,24,62); c.fillText(`dog HP/state: ${dog?.hp ?? '-'} / ${dog?.state ?? '-'}`, 24, 84); c.fillText(`cat HP/state: ${cat?.hp ?? '-'} / ${cat?.state ?? '-'}`, 24, 104); c.fillText(`money:${Math.floor(scene?.economy?.money||0)}/${scene?.economy?.maxMoney||0} dogs:${aliveDogs} cats:${aliveCats}`,24,124); c.fillText(`battleState:${scene?.battleState || '-'} debug:${showParts?'ON':'OFF'} effects:${(scene?.effects||[]).length}`,24,144); }
  drawHpBar(c, actor) { const x = actor.x - 40, y = actor.y - 194, w = 80, h = 8; const ratio = Math.max(0, Math.min(1, actor.hp / Math.max(1, actor.maxHp))); c.fillStyle = '#111827'; c.fillRect(x, y, w, h); c.fillStyle = '#22c55e'; c.fillRect(x, y, w * ratio, h); c.strokeStyle = '#e5e7eb'; c.strokeRect(x, y, w, h); }
  drawActorDebug(c, actor, battleState) { const src = actor.rawStats?.source || {}; const d = actor.debugDistance || {}; const lines = [`${actor.instanceId||'-'} slot:${actor.slotId||'-'} state:${actor.state} battle:${battleState}`,`anim:${actor.currentAnimId} role:${actor.activeAnimRole} target:${actor.currentTargetLabel||'-'} type:${actor.currentTargetType||'-'}`,`bodyDistance:${(d.bodyDistance ?? 0).toFixed(1)} moveSpeed:${(actor.moveSpeed||0).toFixed(1)} sideBlocking:disabled spacing:spawn-only`,`kbElapsed:${(actor.knockbackPositionElapsedMs||0).toFixed(1)} kbDur:${(actor.knockbackPositionDurationMs||0).toFixed(1)} from:${(actor.knockbackFromX||0).toFixed(1)} to:${(actor.knockbackToX||0).toFixed(1)}`,`mappingStatus:${src.mappingStatus || '-'} fallback:${(src.fallbackFields||[]).join('|')||'-'}`]; c.fillStyle = '#0008'; c.fillRect(actor.x - 170, actor.y - 190, 560, 62); c.fillStyle = '#f8fafc'; c.font = '12px ui-monospace, monospace'; lines.forEach((line, i) => c.fillText(line, actor.x - 164, actor.y - 176 + i * 14)); }
  drawEventLog(c, events){c.fillStyle='#0008';c.fillRect(14,170,900,170);c.fillStyle='#fde68a';c.font='13px ui-monospace';c.fillText('battle events (latest 10)',24,190);c.fillStyle='#f8fafc';(events||[]).slice().reverse().forEach((e,i)=>c.fillText(`${Math.round(e.timeMs)} ${e.type} ${e.actor||'-'} -> ${e.target||'-'} ${e.targetType||''} dmg:${e.damage??'-'}`,24,210+i*14));}
  drawActor(c, actor) { if (!actor?.sprite || !actor?.model || !actor.isAlive()) return; const baseAngle = actor.model.baseAngle || 3600; c.save(); c.translate(actor.x, actor.y); if (actor.renderFlipX) c.scale(-1, 1); for (const p of actor.model.getDrawList()) { const w = p.world; const partIndex = p.current?.partIndex ?? p.partIndex; const imgcutIndex = p.current?.imgcutIndex ?? p.imgcutIndex; if (!Number.isInteger(partIndex) || partIndex < 0) continue; if ((imgcutIndex ?? 0) < 0) continue; if (!w || (w.o ?? 1) <= 0) continue; const part = actor.sprite?.imgcut?.parts?.[partIndex]; if (!part || part.w <= 0 || part.h <= 0) continue; c.save(); c.translate(w.x * actor.scale, w.y * actor.scale); c.rotate((w.a / baseAngle) * Math.PI * 2); c.globalAlpha = w.o ?? 1; const sx = w.sx * actor.scale; const sy = w.sy * actor.scale; actor.sprite.drawPart(c, partIndex, -part.w * 0.5 * sx, -part.h * 0.5 * sy, { scaleX: sx, scaleY: sy }); c.restore(); } c.restore(); }
}
