export const BATTLE_CONFIG = {
  groundY: 590,
  tuning: { fps: 30, speedToPxPerSecond: 4.32, rangeToPx: 0.54, battleTimeScale: 0.65, minAttackWaitMs: 450, minAttackAnimMs: 500, knockbackPositionDistance: 50, defaultCollisionRadius: 42, dogCollisionRadius: 46, catCollisionRadius: 42, minVisualGapPx: 18, maxAliveActors: 30, maxAliveActorsPerSide: 15, spawnSeparationPx: 32, deadRemoveAfterMs: 1000, maxEffects: 40 },
  stage: { id: 0, imagePath: './public/assets/bcu/000001/org/img/bg/bg000.png', imgcutPath: './public/assets/bcu/000001/org/battle/bg/bg00.imgcut', csvPath: './public/assets/bcu/000001/org/battle/bg/bg.csv', cropName: '背景bg', groundY: 590, backgroundMode: 'cover-crop' },
  bases: { dogBase: { id: 'dog-base', side: 'dog-player', label: 'ワンコ軍 拠点', x: 1120, y: 590, maxHp: 1000, collisionRadius: 80, visualKind: 'castle-composite', visualAssetId: 'castle-composite-000', scale: 1.0 }, catBase: { id: 'cat-base', side: 'cat-enemy', label: 'ネコ軍 拠点', x: 120, y: 590, maxHp: 1000, collisionRadius: 80, visualKind: 'simple-placeholder', visualAssetId: null, scale: 1.0 } },
  rosters: {
    dogPlayer:[{slotId:'dog-wanko',label:'ワンコ',assetId:'enemy-000',statsType:'enemy',statsId:0,cost:50,cooldownMs:2000,side:'dog-player',direction:-1,facing:-1,renderFlipX:true,collisionRadius:46,scale:1,idleAnimId:'anim01',moveAnimId:'anim00',attackAnimId:'anim02',knockbackAnimId:'anim03',economySource:'provisional-design'},{slotId:'dog-nyoro',label:'ニョロ',assetId:'enemy-001',statsType:'enemy',statsId:1,cost:75,cooldownMs:2800,side:'dog-player',direction:-1,facing:-1,renderFlipX:true,collisionRadius:46,scale:1,idleAnimId:'anim01',moveAnimId:'anim00',attackAnimId:'anim02',knockbackAnimId:'anim03',economySource:'provisional-design'},{slotId:'dog-rei',label:'例のヤツ',assetId:'enemy-002',statsType:'enemy',statsId:2,cost:100,cooldownMs:3500,side:'dog-player',direction:-1,facing:-1,renderFlipX:true,collisionRadius:46,scale:1,idleAnimId:'anim01',moveAnimId:'anim00',attackAnimId:'anim02',knockbackAnimId:'anim03',economySource:'provisional-design'}],
    catEnemy:[{slotId:'cat-basic',label:'ネコ',assetId:'unit-000-f',statsType:'unit',statsId:0,formRow:0,side:'cat-enemy',direction:1,facing:1,renderFlipX:true,collisionRadius:42,scale:1,idleAnimId:'anim01',moveAnimId:'anim00',attackAnimId:'anim02',knockbackAnimId:'anim03'},{slotId:'cat-tank',label:'タンクネコ',assetId:'unit-001-f',statsType:'unit',statsId:1,formRow:0,side:'cat-enemy',direction:1,facing:1,renderFlipX:true,collisionRadius:50,scale:1,idleAnimId:'anim01',moveAnimId:'anim00',attackAnimId:'anim02',knockbackAnimId:'anim03'},{slotId:'cat-battle',label:'バトルネコ',assetId:'unit-002-f',statsType:'unit',statsId:2,formRow:0,side:'cat-enemy',direction:1,facing:1,renderFlipX:true,collisionRadius:44,scale:1,idleAnimId:'anim01',moveAnimId:'anim00',attackAnimId:'anim02',knockbackAnimId:'anim03'}]
  },
  economy:{dogPlayer:{startMoney:150,maxMoney:6000,incomePerSecond:60}},
  enemySpawnSchedule:[{atMs:1000,slotId:'cat-basic'},{atMs:5000,slotId:'cat-basic',repeatMs:5500},{atMs:12000,slotId:'cat-tank',repeatMs:10000},{atMs:20000,slotId:'cat-battle',repeatMs:14000}]
};
