import { BATTLE_CONFIG } from './BattleConfig.js';
import { BattleAttackProfile } from './BattleAttackProfile.js';
import { BattleBodyResolver } from './BattleBodyResolver.js';

export class BattleAttackResolver {
  static getEntityPosBcu(entity){ if(typeof entity?.getBattlePosBcu==='function') return entity.getBattlePosBcu(); return Number.isFinite(entity?.posBcu)?entity.posBcu:null; }
  static hasBcuPositions(attacker,target){ return Number.isFinite(this.getEntityPosBcu(attacker))&&Number.isFinite(this.getEntityPosBcu(target)); }
  static shouldUseBcu(attacker,target){ const mode=BATTLE_CONFIG.tuning?.combatPositionMode; return mode==='bcu-pos' && Number.isFinite(this.getEntityPosBcu(attacker)) && Number.isFinite(this.getEntityPosBcu(target)); }
  static getEntityCombatX(entity){ if(!entity) return null; const box=BattleBodyResolver.getCombatBodyBox(entity); if(Number.isFinite(box?.combatPositionX)) return box.combatPositionX; if(Number.isFinite(box?.frontX)) return box.frontX; if(Number.isFinite(box?.centerX)) return box.centerX; if(Number.isFinite(entity?.x)) return entity.x; return null; }

  static getAttackIntervalBcu(actor,event){ const pos=this.getEntityPosBcu(actor); if(!Number.isFinite(pos)) return null; const dir=Number.isFinite(actor?.direction)?actor.direction:1; const kind=event?.attackKind||event?.raw?.attackKind||'normal'; let p0,p1; if(kind==='ld'||kind==='omni'){ p0=pos+dir*(event?.shortPointBcu??0); p1=pos+dir*(event?.longPointBcu??0);} else { p0=pos+dir*(event?.rangeEndBcu??actor?.detectionRangeBcu??0); p1=pos-dir*(event?.attackBackBcu??actor?.attackWidthBcu??0);} return {leftBcu:Math.min(p0,p1),rightBcu:Math.max(p0,p1),kind,posBcu:pos}; }
  static getTouchIntervalBcu(actor){ return this.getAttackIntervalBcu(actor,{attackKind:'normal',rangeEndBcu:actor?.detectionRangeBcu??0,attackBackBcu:actor?.attackWidthBcu??0}); }
  static getAttackIntervalPx(actor,event){ const posX=this.getEntityCombatX(actor); if(!Number.isFinite(posX)) return null; const dir=Number.isFinite(actor?.direction)?actor.direction:1; const kind=event?.attackKind||event?.raw?.attackKind||'normal'; let p0,p1; if(kind==='ld'||kind==='omni'){ const shortPx=Number.isFinite(event?.shortPointPxDebug)?event.shortPointPxDebug:0; const longPx=Number.isFinite(event?.longPointPxDebug)?event.longPointPxDebug:0; p0=posX+dir*shortPx; p1=posX+dir*longPx; } else { const rangePx=Number.isFinite(event?.rangeEndPxDebug)?event.rangeEndPxDebug:(Number.isFinite(actor?.detectionRangePx)?actor.detectionRangePx:0); const backPx=Number.isFinite(event?.attackBackPxDebug)?event.attackBackPxDebug:(Number.isFinite(actor?.attackWidthPx)?actor.attackWidthPx:((actor?.rawStats?.width??0)*(BATTLE_CONFIG.tuning?.rangeToPx??1))); p0=posX+dir*rangePx; p1=posX-dir*backPx; }
    const left=Math.min(p0,p1),right=Math.max(p0,p1); const box=BattleBodyResolver.getCombatBodyBox(actor);
    return {left,right,startX:left,endX:right,centerY:Number.isFinite(box?.centerY)?box.centerY:(actor?.y??0),top:Number.isFinite(box?.top)?box.top:((actor?.y??0)-80),bottom:Number.isFinite(box?.bottom)?box.bottom:(actor?.y??0),attackKind:kind,mode:'px-fallback',posX,direction:dir}; }

  static isTargetPosInIntervalBcu(target,interval){ const p=this.getEntityPosBcu(target); if(!Number.isFinite(p)||!interval) return false; return p>=interval.leftBcu&&p<=interval.rightBcu; }
  static isTargetPosInIntervalPx(target,interval){ const x=this.getEntityCombatX(target); if(!Number.isFinite(x)||!interval) return false; return x>=interval.left&&x<=interval.right; }
  static isTargetTouchable(attacker,target){ if(this.shouldUseBcu(attacker,target)) return this.isTargetPosInIntervalBcu(target,this.getTouchIntervalBcu(attacker)); const interval=this.getAttackIntervalPx(attacker,{attackKind:'normal',rangeEndPxDebug:attacker?.detectionRangePx??0,attackBackPxDebug:Number.isFinite(attacker?.attackWidthPx)?attacker.attackWidthPx:((attacker?.rawStats?.width??0)*(BATTLE_CONFIG.tuning?.rangeToPx??1))}); return this.isTargetPosInIntervalPx(target,interval); }
  static isTargetInEventRange(attacker,target,event){ if(this.shouldUseBcu(attacker,target)) return this.isTargetPosInIntervalBcu(target,this.getAttackIntervalBcu(attacker,event)); return this.isTargetPosInIntervalPx(target,this.getAttackIntervalPx(attacker,event)); }

  static chooseSingleTarget(attacker,candidates){ const dir=Number.isFinite(attacker?.direction)?attacker.direction:1; const allHaveBcu=(candidates||[]).every(c=>Number.isFinite(this.getEntityPosBcu(c.target)))&&Number.isFinite(this.getEntityPosBcu(attacker)); if(allHaveBcu){ const ap=this.getEntityPosBcu(attacker)??0; return (candidates||[]).slice().sort((a,b)=>{ const ax=this.getEntityPosBcu(a.target)??0; const bx=this.getEntityPosBcu(b.target)??0; const f=dir>0?(ax-bx):(bx-ax); if(f!==0)return f; return Math.abs(ax-ap)-Math.abs(bx-ap); })[0]||null; }
    const ax=this.getEntityCombatX(attacker)??0; return (candidates||[]).slice().sort((a,b)=>{ const txA=this.getEntityCombatX(a.target)??0; const txB=this.getEntityCombatX(b.target)??0; const front=dir>0?(txA-txB):(txB-txA); if(front!==0)return front; return Math.abs(txA-ax)-Math.abs(txB-ax); })[0]||null; }

  static captureTargets({attacker,enemyActors,enemyBase,event}){ const mode=event?.targetMode||'single'; const actorCandidates=(enemyActors||[]).filter((t)=>{ if (typeof t?.isTargetable === 'function') return t.isTargetable(); return !!t?.isAlive?.(); }).filter(t=>this.isTargetInEventRange(attacker,t,event)).map(target=>({target,targetType:'actor',event})); const baseCandidate=enemyBase?.isAlive?.()&&event?.allowBaseHit!==false&&this.isTargetInEventRange(attacker,enemyBase,event)?{target:enemyBase,targetType:'base',event}:null; if(mode==='range'){ const r=[...actorCandidates]; if(baseCandidate)r.push(baseCandidate); return r; } const c=actorCandidates.length?actorCandidates:(baseCandidate?[baseCandidate]:[]); const one=this.chooseSingleTarget(attacker,c); return one?[one]:[]; }

  static getAttackInterval(actor,event){ const firstEvent=event||BattleAttackProfile.ensure(actor)?.events?.[0]; const mode=BATTLE_CONFIG.tuning?.combatPositionMode; const bcu=(mode==='bcu-pos'&&actor?.battleCoordinate)?this.getAttackIntervalBcu(actor,firstEvent):null; if(bcu&&actor?.battleCoordinate){ const left=actor.battleCoordinate.toScreenX(bcu.leftBcu); const right=actor.battleCoordinate.toScreenX(bcu.rightBcu); const box=BattleBodyResolver.getCombatBodyBox(actor); return {...bcu,left,right,startX:left,endX:right,centerY:Number.isFinite(box?.centerY)?box.centerY:(actor?.y??0),top:Number.isFinite(box?.top)?box.top:((actor?.y??0)-80),bottom:Number.isFinite(box?.bottom)?box.bottom:(actor?.y??0),mode:'bcu-projected'}; }
    return this.getAttackIntervalPx(actor,firstEvent); }

  static explainCapture({ attacker, enemyActors = [], enemyBase = null, event = null } = {}){ const interval=this.getAttackInterval(attacker,event); const mode=interval?.mode||'unknown'; const candidates=[]; for(const target of (enemyActors||[])){ const alive=!!target?.isAlive?.(); const x=this.getEntityCombatX(target); const inRange=alive&&this.isTargetInEventRange(attacker,target,event); candidates.push({type:'actor',label:target?.instanceId||target?.label||'-',alive,x:Number.isFinite(x)?x:null,inRange}); }
    if(enemyBase){ const alive=!!enemyBase?.isAlive?.(); const x=this.getEntityCombatX(enemyBase); const inRange=alive&&event?.allowBaseHit!==false&&this.isTargetInEventRange(attacker,enemyBase,event); candidates.push({type:'base',label:enemyBase?.label||'-',alive,x:Number.isFinite(x)?x:null,inRange}); }
    return { mode, interval: interval?{ left:Number.isFinite(interval.left)?interval.left:null, right:Number.isFinite(interval.right)?interval.right:null, centerY:Number.isFinite(interval.centerY)?interval.centerY:null, attackKind:interval.attackKind||null, direction:Number.isFinite(interval.direction)?interval.direction:null }:null, candidates, inRangeCount:candidates.filter(c=>c.inRange).length };
  }

  static runSelfCheck(){ const attacker={x:500,y:520,direction:1,detectionRangePx:100,attackWidthPx:20,combatPositionMode:'screen-combat-point',rawStats:{width:20}}; const targetIn={x:560,y:520,side:'cat-enemy',isAlive:()=>true,collisionRadius:10}; const targetOut={x:700,y:520,side:'cat-enemy',isAlive:()=>true,collisionRadius:10}; const event={attackKind:'normal',targetMode:'single',allowBaseHit:true,rangeEndPxDebug:100,attackBackPxDebug:20,damage:10}; const interval=this.getAttackIntervalPx(attacker,event); const inResult=this.isTargetInEventRange(attacker,targetIn,event); const outResult=this.isTargetInEventRange(attacker,targetOut,event); const captured=this.captureTargets({attacker,enemyActors:[targetIn,targetOut],enemyBase:null,event}); return { ok:!!interval&&Number.isFinite(interval.left)&&Number.isFinite(interval.right)&&inResult===true&&outResult===false&&captured.length===1, interval, inResult, outResult, capturedCount:captured.length }; }

  static getAttackDebugLine(actor,event){ return this.getAttackInterval(actor,event); }
}
