export class BattleSceneRenderer {
  render(previewRenderer, scene, showParts = false) {
    const c = previewRenderer.ctx; const w = previewRenderer.logicalW; const h = previewRenderer.logicalH; const groundY = scene?.groundY || 590;
    c.clearRect(0, 0, w, h);
    if (scene?.stage?.background?.image && scene?.stage?.background?.crop) this.drawBackgroundCropCover(c, scene.stage.background, w, h); else this.drawFallbackBackground(c, w, h, groundY);
    c.strokeStyle = '#ffffff33'; c.lineWidth = 1; c.beginPath(); c.moveTo(0, groundY + 0.5); c.lineTo(w, groundY + 0.5); c.stroke();
    this.drawCastle(c, scene?.castle, groundY);
    for (const actor of (scene?.actors || [])) if (actor.isAlive()) this.drawActor(c, actor);
    for (const actor of (scene?.actors || [])) if (actor.isAlive()) this.drawHpBar(c, actor);
    if (showParts) { for (const actor of (scene?.actors || [])) if (actor.isAlive()) this.drawActorDebug(c, actor, scene?.battleState || 'running'); this.drawEventLog(c, scene?.debugEvents || []); }
    this.drawHud(c, scene, showParts);
  }
  drawBackgroundCropCover(c,bg,w,h){const{image,crop}=bg;const scale=Math.max(w/crop.w,h/crop.h);const dw=crop.w*scale,dh=crop.h*scale;const dx=(w-dw)*0.5,dy=(h-dh)*0.5;c.drawImage(image,crop.x,crop.y,crop.w,crop.h,dx,dy,dw,dh)}
  drawFallbackBackground(c,w,h,groundY){const sky=c.createLinearGradient(0,0,0,groundY);sky.addColorStop(0,'#7dc7ff');sky.addColorStop(1,'#d9f0ff');c.fillStyle=sky;c.fillRect(0,0,w,groundY);c.fillStyle='#c9b78f';c.fillRect(0,groundY,w,h-groundY)}
  drawCastle(c, castle, groundY) { if (!castle?.layers?.length) return; const order = ['bottom', 'middle', 'top']; const ordered = order.map((id) => castle.layers.find((x) => x.id === id)).filter(Boolean); for (const layer of ordered) { const scale = castle.scale || 1; const x = castle.x + (layer.offsetX || 0) * scale - layer.image.width * 0.5 * scale; const y = castle.y + (layer.offsetY || 0) * scale - layer.image.height * scale; c.drawImage(layer.image, x, y, layer.image.width * scale, layer.image.height * scale); } c.strokeStyle = '#313e52'; c.strokeRect(castle.x - 6, groundY - 6, 12, 12); }
  drawHud(c, scene, showParts) { const dog = scene?.actors?.find((a) => a.side === 'dog-player'); const cat = scene?.actors?.find((a) => a.side === 'cat-enemy'); c.fillStyle = '#0008'; c.fillRect(14, 14, 760, 150); c.fillStyle = '#f8fafc'; c.font = '20px ui-sans-serif'; c.fillText('Wanko Battle v0.4', 24, 40); c.font = '14px ui-monospace, monospace'; c.fillText(`dog HP/state: ${dog?.hp ?? '-'} / ${dog?.state ?? '-'}`, 24, 70); c.fillText(`cat HP/state: ${cat?.hp ?? '-'} / ${cat?.state ?? '-'}`, 24, 90); c.fillText(`battleState:${scene?.battleState || '-'} debug:${showParts ? 'ON' : 'OFF'}`, 24, 110); c.fillText('timeScale:0.65 speedToPx:3 rangeToPx:0.6',24,130);} 
  drawHpBar(c, actor) { const x = actor.x - 40, y = actor.y - 194, w = 80, h = 8; const ratio = Math.max(0, Math.min(1, actor.hp / Math.max(1, actor.maxHp))); c.fillStyle = '#111827'; c.fillRect(x, y, w, h); c.fillStyle = '#22c55e'; c.fillRect(x, y, w * ratio, h); c.strokeStyle = '#e5e7eb'; c.strokeRect(x, y, w, h); }
  drawActorDebug(c, actor, battleState) { const src = actor.rawStats?.source || {}; const lines = [`${actor.assetDef?.label || '-'} side:${actor.side} battleState:${battleState}`,`state:${actor.state} hp:${actor.hp}/${actor.maxHp} anim:${actor.currentAnimId} role:${actor.activeAnimRole}`,`attackStartupMs:${actor.attackStartupMs.toFixed(1)} attackWaitMs:${actor.attackWaitMs.toFixed(1)} animMs:${actor.attackAnimDurationMs.toFixed(1)}`,`attackElapsed:${actor.attackElapsedMs.toFixed(1)} waitElapsed:${actor.attackWaitElapsedMs.toFixed(1)} hit:${actor.hasHitInCurrentAttack} cycle:${actor.attackCycleId}`,`mappingStatus:${src.mappingStatus || '-'} fallback:${(src.fallbackFields||[]).join('|')||'-'}`,`battleTimeScale:0.65 moveSpeed:${actor.moveSpeed.toFixed(1)}px/s`]; c.fillStyle = '#0008'; c.fillRect(actor.x - 180, actor.y - 190, 520, 96); c.fillStyle = '#f8fafc'; c.font = '12px ui-monospace, monospace'; lines.forEach((line, i) => c.fillText(line, actor.x - 174, actor.y - 176 + i * 14)); }
  drawEventLog(c, events){c.fillStyle='#0008';c.fillRect(14,170,900,170);c.fillStyle='#fde68a';c.font='13px ui-monospace';c.fillText('battle events (latest 10)',24,190);c.fillStyle='#f8fafc';(events||[]).slice().reverse().forEach((e,i)=>c.fillText(`${Math.round(e.timeMs)} ${e.type} ${e.actor||'-'} -> ${e.target||'-'} dmg:${e.damage??'-'} aState:${e.actorState||'-'} tState:${e.targetState||'-'}`,24,210+i*14));}
  drawActor(c, actor) { if (!actor?.sprite || !actor?.model || !actor.isAlive()) return; const baseAngle = actor.model.baseAngle || 3600; c.save(); c.translate(actor.x, actor.y); if (actor.renderFlipX) c.scale(-1, 1); for (const p of actor.model.getDrawList()) { const w = p.world; const partIndex = p.current?.partIndex ?? p.partIndex; const imgcutIndex = p.current?.imgcutIndex ?? p.imgcutIndex; if (!Number.isInteger(partIndex) || partIndex < 0) continue; if ((imgcutIndex ?? 0) < 0) continue; if (!w || (w.o ?? 1) <= 0) continue; const part = actor.sprite?.imgcut?.parts?.[partIndex]; if (!part || part.w <= 0 || part.h <= 0) continue; c.save(); c.translate(w.x * actor.scale, w.y * actor.scale); c.rotate((w.a / baseAngle) * Math.PI * 2); c.globalAlpha = w.o ?? 1; const sx = w.sx * actor.scale; const sy = w.sy * actor.scale; actor.sprite.drawPart(c, partIndex, -part.w * 0.5 * sx, -part.h * 0.5 * sy, { scaleX: sx, scaleY: sy }); c.restore(); } c.restore(); }
}
