import { BattleBase } from './BattleBase.js';
import { BattleActorFactory } from './BattleActorFactory.js';
import { BattleStatsLoader } from './BattleStatsLoader.js';
import { BattleEconomy } from './BattleEconomy.js';
import { BATTLE_CONFIG } from './BattleConfig.js';
import { BattleEffect } from './BattleEffect.js';
import { BattleEffectLoader } from './BattleEffectLoader.js';
import { StageBackgroundLoader } from './StageBackgroundLoader.js';
import { PREVIEW_ASSETS } from '../data/previewAssets.js';

export class BattleScene {
  constructor(uiLog){this.log=uiLog||(()=>{});this.bgLoader=new StageBackgroundLoader(uiLog);this.statsLoader=new BattleStatsLoader();this.actorFactory=new BattleActorFactory(this.statsLoader,BATTLE_CONFIG.tuning);this.actors=[];this.bases=[];this.actorSerial=0;this.battleState='running';this.timeMs=0;this.debugEvents=[];this.enemySpawnerState=[];this.economy=null;this.effects=[];this.effectLoader=new BattleEffectLoader();this.hitEffectAsset=null;this.groundY=BATTLE_CONFIG.visualLayout?.groundY??BATTLE_CONFIG.groundY;this.actorGroundY=BATTLE_CONFIG.visualLayout?.actorGroundY??this.groundY;this.stage={...BATTLE_CONFIG.stage,background:null,backgroundLoadFailed:false};}
  findAsset(id){return PREVIEW_ASSETS.find(a=>a.id===id)}
  async loadCompositeLayers(asset){const loaded=[];for(const l of (asset.layers||[])){try{const i=new Image();await new Promise((res,rej)=>{i.onload=res;i.onerror=rej;i.src=`${l.baseDir}${l.image}`});loaded.push({id:l.id,offsetX:l.offsetX||0,offsetY:l.offsetY||0,image:i});}catch{}}return loaded;}
  async loadBase(def){const b=new BattleBase(def);if(def.visualKind==='castle-composite'&&def.visualAssetId){const a=this.findAsset(def.visualAssetId);if(a)b.layers=await this.loadCompositeLayers(a);}return b;}
  async preloadRosters(){for(const u of BATTLE_CONFIG.rosters.dogPlayer) await this.actorFactory.preloadTemplate(u); for(const u of BATTLE_CONFIG.rosters.catEnemy) await this.actorFactory.preloadTemplate(u);}
  nextInstanceId(side,unitId){this.actorSerial+=1;const p=side==='dog-player'?'dog':'cat';return `${p}-${unitId.replace(/\D/g,'')||'000'}-${this.actorSerial}`;}
  getDepthLaneForSpawn(){const depth=BATTLE_CONFIG.visualLayout?.actorDepth;const laneCount=Math.max(1,Math.floor(depth?.laneCount??1));if(!depth?.enabled||laneCount<=1)return{laneIndex:0,laneCount:1,yOffset:0,scaleMultiplier:1};const laneIndex=depth.randomizeOnSpawn?Math.floor(Math.random()*laneCount):Math.floor(laneCount/2);const t=laneCount<=1?0:laneIndex/(laneCount-1);const minY=Number.isFinite(depth.minYOffset)?depth.minYOffset:0;const maxY=Number.isFinite(depth.maxYOffset)?depth.maxYOffset:0;const minScale=Number.isFinite(depth.minScaleMultiplier)?depth.minScaleMultiplier:1;const maxScale=Number.isFinite(depth.maxScaleMultiplier)?depth.maxScaleMultiplier:1;return{laneIndex,laneCount,yOffset:minY+(maxY-minY)*t,scaleMultiplier:minScale+(maxScale-minScale)*t};}
  applyVisualDepth(actor,unitDef){const lane=this.getDepthLaneForSpawn();const baseScale=unitDef.scale??1;const globalScale=BATTLE_CONFIG.visualLayout?.actorGlobalScale??1;const laneScale=lane.scaleMultiplier??1;actor.visualDepthLaneIndex=lane.laneIndex;actor.visualDepthLaneCount=lane.laneCount;actor.visualDepthYOffset=lane.yOffset;actor.visualBaseScale=baseScale;actor.visualGlobalScale=globalScale;actor.visualDepthScaleMultiplier=laneScale;actor.y=this.actorGroundY+lane.yOffset;actor.scale=baseScale*globalScale*laneScale;}
  spawnActor(unitDef, side, isPlayerProduced=false){const base=this.bases.find(b=>b.side===side); if(!base)return null; const temp=this.actorFactory.templates.get(unitDef.slotId); const r=unitDef.collisionRadius||42; let x=side==='dog-player'?base.x-base.collisionRadius-r-24:base.x+base.collisionRadius+r+24; const near=this.actors.filter(a=>a.side===side&&a.isAlive()&&Math.abs(a.x-x)<BATTLE_CONFIG.tuning.spawnSeparationPx); if(near.length)x+=(side==='dog-player'?1:-1)*BATTLE_CONFIG.tuning.spawnSeparationPx*near.length; const actor=this.actorFactory.createActor(unitDef.slotId,{side,x,y:this.actorGroundY,direction:unitDef.direction,facing:unitDef.facing,renderFlipX:unitDef.renderFlipX,scale:unitDef.scale,currentAnimId:unitDef.moveAnimId}); this.applyVisualDepth(actor,unitDef); actor.instanceId=this.nextInstanceId(side,unitDef.assetId); actor.spawnedAtMs=this.timeMs; actor.removeAfterMs=1000; actor.slotId=unitDef.slotId; actor.isPlayerProduced=isPlayerProduced; actor.label=unitDef.label; this.actors.push(actor); return actor;}
  requestPlayerSpawn(slotId){const def=BATTLE_CONFIG.rosters.dogPlayer.find(x=>x.slotId===slotId); if(!def||!this.economy.produce(def)) return false; this.spawnActor(def,'dog-player',true); return true;}
  spawnEnemy(slotId){const def=BATTLE_CONFIG.rosters.catEnemy.find(x=>x.slotId===slotId); if(!def)return false; const alive=this.actors.filter(a=>a.isAlive()&&a.side==='cat-enemy').length; if(alive>=BATTLE_CONFIG.tuning.maxAliveActorsPerSide)return false; this.spawnActor(def,'cat-enemy',false); return true;}
  getPlayerRosterStatus(){return BATTLE_CONFIG.rosters.dogPlayer.map(u=>({slotId:u.slotId,label:u.label,cost:u.cost,...this.economy.getStatus(u)}));}
  findEnemyActors(actor){return this.actors.filter(a=>a.side!==actor.side&&a.isAlive());}
  findEnemyBase(actor){return this.bases.find(b=>b.side!==actor.side&&b.isAlive());}
  findTargetForActor(actor){const es=this.findEnemyActors(actor); if(es.length){es.sort((a,b)=>actor.getCenterDistanceTo(a)-actor.getCenterDistanceTo(b));return {target:es[0],targetType:'actor'};} const b=this.findEnemyBase(actor); return b?{target:b,targetType:'base'}:null;}
  canAttack(a,t){return a.getBodyDistanceTo(t)<=a.detectionRangePx;}
  tickKnockback(actor,dt,target){actor.knockbackPositionElapsedMs+=dt; const t=Math.min(1,actor.knockbackPositionElapsedMs/Math.max(1,actor.knockbackPositionDurationMs)); const ease=t*(2-t); actor.x=actor.knockbackFromX+(actor.knockbackToX-actor.knockbackFromX)*ease; if(t>=1){ if(actor.isAlive()&&target&&this.canAttack(actor,target)){actor.setState('attack-wait');actor.setAnimation(actor.idleAnimId,'attack-wait',true);} else {actor.setState('move');actor.setAnimation(actor.moveAnimId,'move',true);} actor.applyCurrentAnimationFrame(); }}
  resolveSameSideSpacing(){for(const side of ['dog-player','cat-enemy']){const arr=this.actors.filter(a=>a.side===side&&a.isAlive()).sort((a,b)=>a.x-b.x); for(let i=1;i<arr.length;i++){const prev=arr[i-1],cur=arr[i];const min=BATTLE_CONFIG.tuning.spawnSeparationPx; if(Math.abs(cur.x-prev.x)<min) cur.x=prev.x+min;}}}
  cleanupDead(){this.actors=this.actors.filter(a=>a.isAlive()||((a.deadAtMs??(a.deadAtMs=this.timeMs)), this.timeMs-a.deadAtMs<a.removeAfterMs));}
  tickEffects(dt){for(const e of this.effects)e.tick(dt);}
  cleanupEffects(){this.effects=this.effects.filter(e=>!e.finished);}
  spawnHitEffect(attacker,target,targetType){if(!this.hitEffectAsset?.parts?.length)return; const dir=Math.sign(target.x-attacker.x)||attacker.direction||1; const x=target.x-dir*(target.collisionRadius||0); const y=targetType==='base'?target.y-120:target.y-80; const scale=targetType==='base'?1.2:1.0; if(this.effects.length>=BATTLE_CONFIG.tuning.maxEffects)return; this.effects.push(new BattleEffect({id:`fx-${this.timeMs}-${Math.random()}`,x,y,frameParts:this.hitEffectAsset.parts,image:this.hitEffectAsset.image,scale}));}
  updateBattleState(){const dog=this.bases.find(b=>b.side==='dog-player');const cat=this.bases.find(b=>b.side==='cat-enemy');if(dog.destroyed&&cat.destroyed)this.battleState='draw'; else if(dog.destroyed)this.battleState='cat-win'; else if(cat.destroyed)this.battleState='dog-win'; else this.battleState='running';}
  async init(){this.actors=[];this.bases=[];this.actorSerial=0;this.timeMs=0;this.debugEvents=[];this.battleState='running';this.economy=new BattleEconomy(BATTLE_CONFIG.economy.dogPlayer);this.enemySpawnerState=BATTLE_CONFIG.enemySpawnSchedule.map((s)=>({...s,nextAtMs:s.atMs})); this.stage={...BATTLE_CONFIG.stage,background:null,backgroundLoadFailed:false}; try{this.stage.background=await this.bgLoader.load(BATTLE_CONFIG.stage);}catch{this.stage.backgroundLoadFailed=true;} await this.preloadRosters(); try{this.hitEffectAsset=await this.effectLoader.loadHitEffect();}catch{this.hitEffectAsset=null;} this.bases=[await this.loadBase(BATTLE_CONFIG.bases.dogBase),await this.loadBase(BATTLE_CONFIG.bases.catBase)]; this.spawnActor(BATTLE_CONFIG.rosters.dogPlayer[0],'dog-player',true); this.spawnActor(BATTLE_CONFIG.rosters.catEnemy[0],'cat-enemy',false);}
  tick(dt){if(this.battleState!=='running')return;const e=dt*BATTLE_CONFIG.tuning.battleTimeScale;this.timeMs+=e;this.economy.tick(e); for(const s of this.enemySpawnerState){if(this.timeMs>=s.nextAtMs){this.spawnEnemy(s.slotId); if(s.repeatMs)s.nextAtMs+=s.repeatMs; else s.nextAtMs=Infinity;}}
    const queue=[]; for(const a of this.actors){if(!a.isAlive())continue; a.tick(e); const sel=this.findTargetForActor(a); if(!sel)continue; const {target,targetType}=sel; a.currentTargetLabel=target.label;a.currentTargetType=targetType; if(a.state==='knockback'){ this.tickKnockback(a,e,target); continue; } if(!this.canAttack(a,target)){a.setState('move');a.setAnimation(a.moveAnimId,'move');a.x+=a.direction*a.moveSpeed*(e/1000); continue;} if(a.state==='move'){a.setState('attack');a.setAnimation(a.attackAnimId,'attack',true);a.applyCurrentAnimationFrame();} if(a.state==='attack'){const prev=a.attackElapsedMs;a.attackElapsedMs+=e; const hit=!a.hasHitInCurrentAttack&&(a.attackStartupMs<=0?a.attackElapsedMs>0:(prev<a.attackStartupMs&&a.attackElapsedMs>=a.attackStartupMs)); if(hit){a.hasHitInCurrentAttack=true; queue.push({attacker:a,target,targetType,damage:a.damage});} if(a.attackElapsedMs>=Math.max(a.attackAnimDurationMs,a.attackStartupMs)){a.setState('attack-wait');a.setAnimation(a.idleAnimId,'attack-wait',true);a.applyCurrentAnimationFrame();}} else if(a.state==='attack-wait'){a.attackWaitElapsedMs+=e; if(a.attackWaitElapsedMs>=a.nextAttackReadyMs){a.setState('attack');a.setAnimation(a.attackAnimId,'attack',true);a.applyCurrentAnimationFrame();}}
    }
    for(const q of queue){const before=q.target.hp;const result=q.target.takeDamage(q.damage);this.spawnHitEffect(q.attacker,q.target,q.targetType); if(q.targetType==='actor'&&result?.knockedBack)this.pushEvent?.({type:'knockbackStart',actor:q.target.instanceId||q.target.label,timeMs:this.timeMs}); if(q.targetType==='actor'&&result?.dead)this.pushEvent?.({type:'dead',actor:q.target.instanceId||q.target.label,timeMs:this.timeMs}); if(q.targetType==='base'&&result?.destroyed)this.pushEvent?.({type:'baseDestroyed',target:q.target.label,timeMs:this.timeMs}); } this.tickEffects(e); this.cleanupEffects(); this.cleanupDead(); this.updateBattleState();
  }
}
