import { BcuKbeffLoader, verifyKbeffAssetPaths } from './BcuKbeffLoader.js';
import { sampleKbeffTransform } from './BcuKbeffRuntime.js';
import { BattleScene } from './BattleScene.js';
import { BATTLE_CONFIG } from './BattleConfig.js';
import { BattleBodyResolver } from './BattleBodyResolver.js';

export async function verifyKbeffAssets() { return verifyKbeffAssetPaths(BATTLE_CONFIG.tuning?.knockback?.kbEffect?.baseDir); }
const approx=(a,b,t=0.001)=>Math.abs(a-b)<=t;
export async function verifyKbeffMaanimSamples(){const l=new BcuKbeffLoader();await l.loadAll();const hb=l.getDefinition('INT_HB'),sw=l.getDefinition('INT_SW'),ass=l.getDefinition('INT_ASS');const checks=[['hb0',sampleKbeffTransform(hb,0).localY,0],['hb8',sampleKbeffTransform(hb,8).localY,-50],['hb16',sampleKbeffTransform(hb,16).localY,0],['hb20',sampleKbeffTransform(hb,20).localY,-25],['hb24',sampleKbeffTransform(hb,24).localY,0],['sw16',sampleKbeffTransform(sw,16).localY,-100],['sw40',sampleKbeffTransform(sw,40).localY,-50],['ass6',sampleKbeffTransform(ass,6).localY,-25]];const failed=checks.filter(([_,v,e])=>!approx(v,e));return{ok:!failed.length,failed,checks};}
export async function verifyKbeffRuntime(){const l=new BcuKbeffLoader();await l.loadAll();const rt=l.createVerifiedRuntime('INT_HB');rt.reset();for(let i=0;i<8;i++)rt.stepFrame();const t=rt.getParentTransform(1.5);return{ok:t.localY===-50&&t.screenYDebug===-75&&t.screenYDebug<0,t};}
export async function verifyKbeffBattleIntegration(){const s=new BattleScene();await s.init();const a=s.actors.find(x=>x.side==='cat-enemy')||s.actors[0];const cfg=a.getKnockbackConfig(BATTLE_CONFIG.tuning,'hp');a.startKnockback({...cfg,nowMs:0,kbeffRuntime:s.createKbeffRuntimeForKb(cfg.bcuType),kbeffInitialUpdate:true});const c0=BattleBodyResolver.getActorCombatPositionX(a);const b0=a.getCombatBodyBox();while(a.kbMoveFramesRemaining>0)a.stepKnockbackFrame();s.finishKnockback(a,null);const b1=a.getCombatBodyBox();return{ok:a.kbeffEnabled===false&&a.kbeffParentTransform===null&&approx(c0,BattleBodyResolver.getActorCombatPositionX(a)-(a.knockbackFromX-a.x),1e-3)&&approx(b0.centerY,b1.centerY,1e-3)};}
export async function printKbeffSamples(){const r=await verifyKbeffMaanimSamples();console.log(r.checks.map(([k,v])=>({k,v})));}
export async function printBcuKbeffVisualTrace(){const s=new BattleScene();await s.init();const a=s.actors.find(x=>x.side==='cat-enemy')||s.actors[0];const cfg=a.getKnockbackConfig(BATTLE_CONFIG.tuning,'hp');a.startKnockback({...cfg,nowMs:0,kbeffRuntime:s.createKbeffRuntimeForKb(cfg.bcuType),kbeffInitialUpdate:true});const trace=[];trace.push({step:'start',kf:a.kbeffFrame,localY:a.kbeffParentTransform?.localY,anim:a.currentAnimId,role:a.activeAnimRole});for(let i=0;i<10&&a.kbMoveFramesRemaining>0;i++){a.stepKnockbackFrame();trace.push({step:i+1,kf:a.kbeffFrame,localY:a.kbeffParentTransform?.localY,x:a.x});}console.log(trace);}
export async function verifyBcuKbeffVisualParity(){const s=new BattleScene();await s.init();const a=s.actors.find(x=>x.side==='cat-enemy')||s.actors[0];const cfg=a.getKnockbackConfig(BATTLE_CONFIG.tuning,'hp');a.startKnockback({...cfg,nowMs:0,kbeffRuntime:s.createKbeffRuntimeForKb(cfg.bcuType),kbeffInitialUpdate:true});const startOk=a.kbeffEnabled&&a.kbeffType==='INT_HB'&&a.kbeffFrame===1&&a.currentAnimId!==a.knockbackAnimId;let peak=false;for(let i=0;i<10&&a.kbMoveFramesRemaining>0;i++){a.stepKnockbackFrame();if((a.kbeffParentTransform?.localY??0)<=-50)peak=true;}while(a.kbMoveFramesRemaining>0)a.stepKnockbackFrame();s.finishKnockback(a,null);const finishOk=!a.kbeffEnabled&&a.kbeffParentTransform===null;const visualOk=a.kbVisualOffsetX===0&&a.kbVisualOffsetY===0&&a.kbVisualScale===1;return{ok:startOk&&peak&&finishOk&&visualOk,startOk,peak,finishOk,visualOk,moveFrames:a.kbMoveFramesTotal,bcuFrames:a.kbBcuTimeFrames};}

function refEase2(t,p){ if(p>=0) return 1-Math.sqrt(Math.max(0,1-Math.pow(t,p||1))); return Math.sqrt(Math.max(0,1-Math.pow(1-t,-p))); }
function referenceBcuPartValueAt(track,frame){ const k=track.keyframes||[]; if(frame<=k[0].frame)return Math.trunc(k[0].value); for(let i=0;i<k.length-1;i++){const a=k[i],b=k[i+1]; if(frame===a.frame)return Math.trunc(a.value); if(frame>a.frame&&frame<b.frame){ const t=(frame-a.frame)/(b.frame-a.frame); const ti=a.easing===2?refEase2(t,a.parameter||0):(a.easing===1?0:t); return Math.trunc(a.value+(b.value-a.value)*ti);} } return Math.trunc(k[k.length-1].value);}
export async function printBcuMaanimInterpolationTrace(){ const l=new BcuKbeffLoader(); await l.loadAll(); const tr=l.getDefinition('INT_HB').anim.tracks.find(t=>t.modification===5&&t.partId===1); const fs=[1,2,4,6,8,10,12,14,16,18,20,22,24]; console.log(fs.map(f=>({f,ref:referenceBcuPartValueAt(tr,f)}))); }
export async function verifyBcuMaanimInterpolationSamples(){ const l=new BcuKbeffLoader(); await l.loadAll(); const hb=l.getDefinition('INT_HB'); const tr=hb.anim.tracks.find(t=>t.modification===5&&t.partId===1); const fs=[1,2,4,6,8,10,12,14,16,18,20,22,24]; const diffs=[]; for(const f of fs){ const ref=referenceBcuPartValueAt(tr,f); const rt=sampleKbeffTransform(hb,f).localY; if(ref!==rt)diffs.push({f,ref,rt}); } return {ok:diffs.length===0,diffs}; }
export async function verifyKbeffParentMatrixParity(){ const l=new BcuKbeffLoader(); await l.loadAll(); const rt=l.createVerifiedRuntime('INT_HB'); rt.reset(); rt.stepFrame(); const t=rt.getParentTransform(); return {ok:Array.isArray(t.matrix)&&t.matrix.length===6&&t.source.includes('matrix'),t}; }

export async function getKbeffVerificationStatus(){const assets=await verifyKbeffAssets();const key=await verifyKbeffMaanimSamples();const interp=await verifyBcuMaanimInterpolationSamples();const pm=await verifyKbeffParentMatrixParity();const exactMaanimOk=!!(key.ok&&interp.ok);const parentMatrixOk=!!pm.ok;const assetsOk=!!assets.ok;const ok=assetsOk&&exactMaanimOk&&parentMatrixOk;return {ok,exactMaanimOk,parentMatrixOk,assetsOk,canEnableRuntime:ok};}
export async function verifyKbeffCanBeEnabled(){return getKbeffVerificationStatus();}
