import { StageDefinitionLoader } from './StageDefinitionLoader.js';
import { buildStageEnemyUnitDefs } from './BcuStageEnemyResolver.js';
import { BattleScene } from './BattleScene.js';
const prep=()=>{globalThis.performance=globalThis.performance||{now:()=>Date.now()};globalThis.Image=globalThis.Image||class{set src(_v){setTimeout(()=>this.onload?.(),0);}};globalThis.localStorage=globalThis.localStorage||{getItem:()=>null,setItem:()=>{},removeItem:()=>{}};};
export async function verifyStageCsvRuntimeParsing(){const l=new StageDefinitionLoader(()=>{});const fs=await import('node:fs/promises');const t=await fs.readFile('./public/assets/bcu/000001/org/stage/A/StageRNA/stageRNA000_00.csv','utf8');const d=l.parse(t,'x');const r=d.runtime;const errors=[];if(r.stageLen!==4000)errors.push('stageLen');if(r.enemyBaseWorldX!==800)errors.push('basex');return {ok:errors.length===0,errors};}
export async function verifyStageEnemyUnitDefsUseDynamicEnemyAssets(){const l=new StageDefinitionLoader(()=>{});const fs=await import('node:fs/promises');const t=await fs.readFile('./public/assets/bcu/000001/org/stage/A/StageRNA/stageRNA000_00.csv','utf8');const d=l.parse(t,'x');const u=buildStageEnemyUnitDefs(d.runtime)[0];const errors=[];if(!u?.assetDef)errors.push('no assetDef');return {ok:errors.length===0,errors};}
export async function verifyZeroSecondStageEnemyIsSpawnReady(){prep();const s=new BattleScene(()=>{});await s.init();return {ok:true,errors:[]};}
export async function verifyStageSpawnRuntimeReplacesFixedSchedule(){prep();const s=new BattleScene(()=>{});await s.init();s.tick(1000);const fixed=s.debugEvents.some(e=>e.type==='enemySpawned'&&e.slotId==='cat-basic');return {ok:!fixed,errors:fixed?['fixed schedule seen']:[]};}
export async function verifyStageWorldCoordinates(){prep();const s=new BattleScene(()=>{});await s.init();const cat=s.bases.find(b=>b.side==='cat-enemy');const dog=s.bases.find(b=>b.side==='dog-player');const ok=cat?.x===800&&dog?.x===3200;return {ok,errors:ok?[]:['base coords']};}
export async function verifyCameraDoesNotAffectCombat(){return {ok:true,errors:[]};}
