export class BattleCameraInputController {
  constructor(canvas, getCamera, options = {}) { this.canvas = canvas; this.getCamera = getCamera; this.options = options; this.active = new Map(); this.lastInputDebug = null; this._onDown=this.onDown.bind(this); this._onMove=this.onMove.bind(this); this._onUp=this.onUp.bind(this); this._onWheel=this.onWheel.bind(this); }
  attach(){ if(!this.canvas) return; this.canvas.style.touchAction='none'; this.canvas.style.overscrollBehavior='none'; this.canvas.addEventListener('pointerdown',this._onDown); this.canvas.addEventListener('pointermove',this._onMove); this.canvas.addEventListener('pointerup',this._onUp); this.canvas.addEventListener('pointercancel',this._onUp); this.canvas.addEventListener('lostpointercapture',this._onUp); this.canvas.addEventListener('wheel',this._onWheel,{passive:false}); }
  detach(){ if(!this.canvas) return; this.canvas.removeEventListener('pointerdown',this._onDown); this.canvas.removeEventListener('pointermove',this._onMove); this.canvas.removeEventListener('pointerup',this._onUp); this.canvas.removeEventListener('pointercancel',this._onUp); this.canvas.removeEventListener('lostpointercapture',this._onUp); this.canvas.removeEventListener('wheel',this._onWheel); this.active.clear(); }
  getCanvasRect(){return this.canvas?.getBoundingClientRect?.()||null;}
  getLogicalW(rect){return this.options?.logicalW||this.getCamera?.()?.logicalW||this.canvas?.width||rect?.width||1;}
  getCanvasLogicalX(clientX){const rect=this.getCanvasRect();const logicalW=this.getLogicalW(rect);if(!rect||rect.width<=0)return clientX;return ((clientX-rect.left)/rect.width)*logicalW;}
  getCanvasLogicalDeltaX(clientDeltaX){const rect=this.getCanvasRect();const logicalW=this.getLogicalW(rect);if(!rect||rect.width<=0)return clientDeltaX;return (clientDeltaX/rect.width)*logicalW;}
  recordInputDebug(type,{clientX=null,logicalX=null,clientDeltaX=null,logicalDeltaX=null}={}){const rect=this.getCanvasRect();const cam=this.getCamera?.();this.lastInputDebug={type,clientX,logicalX,clientDeltaX,logicalDeltaX,canvasLeft:rect?.left??null,canvasWidth:rect?.width??null,logicalW:this.getLogicalW(rect),cameraPos:cam?.pos??null,cameraZoom:cam?.zoom??cam?.siz??null};}
  onDown(e){ this.canvas.setPointerCapture?.(e.pointerId); this.active.set(e.pointerId,{x:e.clientX,y:e.clientY,px:e.clientX,py:e.clientY}); }
  onMove(e){ if(!this.active.has(e.pointerId)) return; const p=this.active.get(e.pointerId); p.px=p.x; p.py=p.y; p.x=e.clientX; p.y=e.clientY; const cam=this.getCamera?.(); if(!cam) return;
    const pts=[...this.active.values()]; if(pts.length===1){ const clientDx=p.x-p.px; const logicalDx=this.getCanvasLogicalDeltaX(clientDx); this.recordInputDebug('pointer-pan',{clientDeltaX:clientDx,logicalDeltaX:logicalDx}); cam.panByScreenDelta(logicalDx); return; }
    if(pts.length>=2){ const [a,b]=pts; const prev=Math.hypot(a.px-b.px,a.py-b.py); const cur=Math.hypot(a.x-b.x,a.y-b.y); if(prev>0&&cur>0){ const centerClientX=(a.x+b.x)*0.5; const centerLogicalX=this.getCanvasLogicalX(centerClientX); this.recordInputDebug('pinch-zoom',{clientX:centerClientX,logicalX:centerLogicalX}); cam.zoomAtScreenPoint(centerLogicalX, (cam.siz??cam.zoom??1)*(cur/prev)); } }
  }
  onUp(e){ this.active.delete(e.pointerId); }
  onWheel(e){ const cam=this.getCamera?.(); if(!cam) return; e.preventDefault(); if(e.ctrlKey||e.metaKey){ const logicalX=this.getCanvasLogicalX(e.clientX); this.recordInputDebug('wheel-zoom',{clientX:e.clientX,logicalX}); const bcuExp=0.9; cam.zoomAtScreenPoint(logicalX, (cam.siz??cam.zoom??1)*(e.deltaY<0?1/bcuExp:bcuExp)); } else { const rawDelta=-(e.deltaX||e.deltaY); const logicalDeltaX=this.getCanvasLogicalDeltaX(rawDelta); this.recordInputDebug('wheel-pan',{clientDeltaX:rawDelta,logicalDeltaX}); cam.panByScreenDelta(logicalDeltaX); } }
}
